
#Machine Energy Usage Config. This config is synced from server to client.
[usage]
	#Energy per operation tick (Joules).
	enrichmentChamber = "50"
	#Energy per operation tick (Joules).
	osmiumCompressor = "50"
	#Energy per operation tick (Joules).
	combiner = "50"
	#Energy per operation tick (Joules).
	crusher = "50"
	#Energy per operation tick (Joules).
	metallurgicInfuser = "50"
	#Energy per operation tick (Joules).
	purificationChamber = "50"
	#Energy per operation tick (Joules).
	energizedSmelter = "50"
	#Energy per operation tick (Joules).
	digitalMiner = "1000"
	#Energy per operation tick (Joules).
	electricPump = "50"
	#Energy that can be transferred at once per charge operation (Joules).
	chargePad = "1024000"
	#Energy per operation tick (Joules).
	rotaryCondensentrator = "1"
	#Energy per operation tick (Joules).
	oxidationChamber = "50"
	#Energy per operation tick (Joules).
	chemicalInfuser = "50"
	#Energy per operation tick (Joules).
	chemicalInjectionChamber = "50"
	#Energy per operation tick (Joules).
	precisionSawmill = "50"
	#Energy per operation tick (Joules).
	chemicalDissolutionChamber = "50"
	#Energy per operation tick (Joules).
	chemicalWasher = "50"
	#Energy per operation tick (Joules).
	chemicalCrystallizer = "50"
	#Energy per operation tick (Joules).
	seismicVibrator = "50"
	#Energy per operation tick (Joules).
	pressurizedReactionBase = "50"
	#Energy per operation tick (Joules).
	fluidicPlenisher = "50"
	#Energy per operation tick (Joules).
	laser = "1000"
	#Energy per operation tick (Joules).
	formulaicAssemblicator = "50"
	#Energy per operation tick (Joules).
	modificationStation = "50"
	#Energy per operation tick (Joules).
	isotopicCentrifuge = "50"
	#Energy per operation tick (Joules).
	nutritionalLiquifier = "50"
	#Energy per operation tick (Joules).
	antiprotonicNucleosynthesizer = "1000"
	#Energy per operation tick (Joules).
	pigmentExtractor = "50"
	#Energy per operation tick (Joules).
	pigmentMixer = "50"
	#Energy per operation tick (Joules).
	paintingMachine = "50"
	#Energy per chunk per tick (Joules).
	dimensionalStabilizer = "5000"

	#Teleporter
	[usage.teleporter]
		#Base Joules cost for a teleportation.
		teleporterBase = "1000"
		#Joules per unit of distance travelled during teleportation - sqrt(xDiff^2 + yDiff^2 + zDiff^2).
		teleporterDistance = "10"
		#Flat additional cost for interdimensional teleportation. Distance is still taken into account minimizing energy cost based on dimension scales.
		teleporterDimensionPenalty = "10000"

