// Custom Items for ModFart
StartupEvents.registry("item", e => {
  //#region - Interne à ModFart
  e.create("blank_template_trim").displayName("Blank Template Trim");
  e.create("blank_template_upgrade").displayName("Blank Template Upgrade");
  e.create("basical_apparatus").displayName("Basical Apparatus");
  e.create("magical_apparatus").displayName("Magical Apparatus");
  e.create("mechanical_apparatus").displayName("Mechanical Apparatus");
  e.create("vital_apparatus").displayName("Vital Apparatus");
  e.create("alloy_creative").displayName("Creative Alloy");
  e.create("creative_control_circuit").displayName("Creative Control Circuit");
  //#endregion

  //#region - Gears/Plates/Rods
  e.create("amethyst_plate").displayName("Amethyst Plate");
  e.create("amethyst_rod").displayName("Amethyst Rod");
  e.create("andesite_gear").displayName("Andesite Gear");
  e.create("andesite_plate").displayName("Andesite Plate");
  e.create("andesite_rod").displayName("Andesite Rod");
  e.create("antimatter_gear").displayName("Antimatter Gear");
  e.create("antimatter_plate").displayName("Antimatter Plate");
  e.create("antimatter_rod").displayName("Antimatter Rod");
  e.create("arcane_gold_rod").displayName("Arcane Gold Rod");
  e.create("arctic_rod").displayName("Arctic Rod");
  e.create("ash_gear").displayName("Ash Gear");
  e.create("ash_rod").displayName("Ash Rod");
  e.create("bedrock_plate").displayName("Bedrock Plate");
  e.create("bismuth_plate").displayName("Bismuth Plate");
  e.create("black_iron_plate").displayName("Black Iron Plate");
  e.create("brass_gear").displayName("Brass Gear");
  e.create("brass_plate").displayName("Brass Plate");
  e.create("brass_rod").displayName("Brass Rod");
  e.create("bronze_gear").displayName("Bronze Gear");
  e.create("bronze_rod").displayName("Bronze Rod");
  e.create("cloggrum_rod").displayName("Cloggrum Rod");
  e.create("coal_gear").displayName("Coal Gear");
  e.create("coal_plate").displayName("Coal Plate");
  e.create("coal_rod").displayName("Coal Rod");
  e.create("copper_gear").displayName("Copper Gear");
  e.create("copper_plate").displayName("Copper Plate");
  e.create("copper_rod").displayName("Copper Rod");
  e.create("crystaltine_gear").displayName("Crystaltine Gear");
  e.create("crystaltine_plate").displayName("Crystaltine Plate");
  e.create("crystaltine_rod").displayName("Crystaltine Rod");
  e.create("deep_gear").displayName("Deep Gear");
  e.create("deep_plate").displayName("Deep Plate");
  e.create("deep_rod").displayName("Deep Rod");
  e.create("diamond_gear").displayName("Diamond Gear");
  e.create("diamond_plate").displayName("Diamond Plate");
  e.create("diamond_rod").displayName("Diamond Rod");
  e.create("dimensional_gear").displayName("Dimensional Gear");
  e.create("dimensional_plate").displayName("Dimensional Plate");
  e.create("dimensional_rod").displayName("Dimensional Rod");
  e.create("dragon_gear").displayName("Dragon Gear");
  e.create("dragon_plate").displayName("Dragon Plate");
  e.create("dragon_rod").displayName("Dragon Rod");
  e.create("drygmy_gear").displayName("Drygmy Gear");
  e.create("drygmy_plate").displayName("Drygmy Plate");
  e.create("drygmy_rod").displayName("Drygmy Rod");
  e.create("echo_gear").displayName("Echo Gear");
  e.create("echo_plate").displayName("Echo Plate");
  e.create("echo_rod").displayName("Echo Rod");
  e.create("electrum_plate").displayName("Electrum Plate");
  e.create("electrum_rod").displayName("Electrum Rod");
  e.create("emerald_gear").displayName("Emerald Gear");
  e.create("emerald_plate").displayName("Emerald Plate");
  e.create("emerald_rod").displayName("Emerald Rod");
  e.create("ender_gear").displayName("Ender Gear");
  e.create("ender_plate").displayName("Ender Plate");
  e.create("ender_rod").displayName("Ender Rod");
  e.create("endumium_gear").displayName("Endumium Gear");
  e.create("endumium_plate").displayName("Endumium Plate");
  e.create("endumium_rod").displayName("Endumium Rod");
  e.create("enhanced_ender_gear").displayName("Enhanced Ender_Gear");
  e.create("enhanced_ender_plate").displayName("Enhanced Ender_Plate");
  e.create("enhanced_ender_rod").displayName("Enhanced Ender_Rod");
  e.create("enhanced_redstone_gear").displayName("Enhanced Redstone Gear");
  e.create("enhanced_redstone_plate").displayName("Enhanced Redstone Plate");
  e.create("enhanced_redstone_rod").displayName("Enhanced Redstone Rod");
  e.create("experience_gear").displayName("Experience Gear").glow(true);
  e.create("experience_plate").displayName("Experience Plate").glow(true);
  e.create("experience_rod").displayName("Experience Rod").glow(true);
  e.create("fiery_rod").displayName("Fiery Rod");
  e.create("flint_plate").displayName("Flint Plate");
  e.create("flint_rod").displayName("Flint Rod");
  e.create("forgotten_rod").displayName("Forgotten Rod");
  e.create("glowstone_rod").displayName("Glowstone Rod");
  e.create("gold_gear").displayName("Gold Gear");
  e.create("gold_plate").displayName("Gold Plate");
  e.create("gold_rod").displayName("Gold Rod");
  e.create("hdpe_gear").displayName("HDPE Gear");
  e.create("hdpe_plate").displayName("HDPE Plate");
  e.create("hdpe_rod").displayName("HDPE Rod");
  e.create("honey_gear").displayName("Honey Gear");
  e.create("honey_plate").displayName("Honey Plate");
  e.create("honey_rod").displayName("Honey Rod");
  e.create("ignitium_rod").displayName("Ignitium Rod");
  e.create("iron_gear").displayName("Iron Gear");
  e.create("iron_plate").displayName("Iron Plate");
  e.create("iron_rod").displayName("Iron Rod");
  e.create("lapis_lazuli_gear").displayName("Lapis Lazuli Gear");
  e.create("lapis_lazuli_plate").displayName("Lapis Lazuli Plate");
  e.create("lapis_lazuli_rod").displayName("Lapis Lazuli Rod");
  e.create("lead_gear").displayName("Lead Gear");
  e.create("malachite_plate").displayName("Malachite Plate");
  e.create("neptunium_rod").displayName("Neptunium Rod");
  e.create("nether_quartz_plate").displayName("Nether Quartz Plate");
  e.create("nether_quartz_rod").displayName("Nether Quartz Rod");
  e.create("nether_star_gear").displayName("Nether Star Gear").glow(true);
  e.create("nether_star_plate").displayName("Nether Star Plate").glow(true);
  e.create("netherite_gear").displayName("Netherite Gear");
  e.create("netherite_plate").displayName("Netherite Plate");
  e.create("netherite_rod").displayName("Netherite Rod");
  e.create("obsidian_plate").displayName("Obsidian Plate");
  e.create("osmium_gear").displayName("Osmium Gear");
  e.create("osmium_plate").displayName("Osmium Plate");
  e.create("paper_plate").displayName("Paper Plate");
  e.create("pewter_gear").displayName("Pewter Gear");
  e.create("pewter_rod").displayName("Pewter Rod");
  e.create("phantom_rod").displayName("Phantom Rod");
  e.create("plutonium_gear").displayName("Plutonium Gear");
  e.create("polonium_gear").displayName("Polonium Gear");
  e.create("prismarine_crystals_gear").displayName("Prismarine Crystals Gear");
  e.create("prismarine_crystals_plate").displayName("Prismarine Crystals Plate");
  e.create("prismarine_crystals_rod").displayName("Prismarine Crystals Rod");
  e.create("quartz_enriched_gear").displayName("Quartz Enriched Iron Gear");
  e.create("redstone_plate").displayName("Redstone Plate");
  e.create("redstone_rod").displayName("Redstone Rod");
  e.create("refined_glowstone_gear").displayName("Refined Glowstone Gear");
  e.create("refined_glowstone_plate").displayName("Refined Glowstone Plate");
  e.create("refined_glowstone_rod").displayName("Refined Glowstone Rod");
  e.create("refined_obsidian_gear").displayName("Refined Obsidian Gear");
  e.create("refined_obsidian_plate").displayName("Refined Obsidian Plate");
  e.create("refined_obsidian_rod").displayName("Refined Obsidian Rod");
  e.create("rose_quartz_gear").displayName("Rose Quartz Gear");
  e.create("rose_quartz_plate").displayName("Rose Quartz Plate");
  e.create("rose_quartz_rod").displayName("Rose Quartz Rod");
  e.create("ruby_plate").displayName("Ruby Plate");
  e.create("scute_gear").displayName("Scute Gear");
  e.create("scute_plate").displayName("Scute Plate");
  e.create("scute_rod").displayName("Scute Rod");
  e.create("sea_gear").displayName("Sea Gear");
  e.create("sea_plate").displayName("Sea Plate");
  e.create("sea_rod").displayName("Sea Rod");
  e.create("shadow_steel_plate").displayName("Shadow Steel Plate");
  e.create("silicon_plate").displayName("Silicon Plate");
  e.create("silver_plate").displayName("Silver Plate");
  e.create("source_gear").displayName("Source Gear");
  e.create("starbuncle_gear").displayName("Starbuncle Gear");
  e.create("starbuncle_plate").displayName("Starbuncle Plate");
  e.create("starbuncle_rod").displayName("Starbuncle Rod");
  e.create("steel_gear").displayName("Steel Gear");
  e.create("steel_plate").displayName("Steel Plate");
  e.create("steel_rod").displayName("Steel Rod");
  e.create("straddlite_gear").displayName("Straddlite Gear");
  e.create("straddlite_plate").displayName("Straddlite Plate");
  e.create("straddlite_rod").displayName("Straddlite Rod");
  e.create("the_ultimate_gear").displayName("The Ultimate Gear");
  e.create("the_ultimate_plate").displayName("The Ultimate Plate");
  e.create("the_ultimate_rod").displayName("The Ultimate Rod");
  e.create("tin_gear").displayName("Tin Gear");
  e.create("titan_gear").displayName("Titan Gear");
  e.create("titan_rod").displayName("Titan Rod");
  e.create("tungsten_plate").displayName("Tungsten Plate");
  e.create("uranium_gear").displayName("Uranium Gear");
  e.create("void_steel_gear").displayName("Void Steel Gear");
  e.create("void_steel_plate").displayName("Void Steel Plate");
  e.create("whirlisprig_gear").displayName("Whirlisprig Gear");
  e.create("whirlisprig_plate").displayName("Whirlisprig Plate");
  e.create("whirlisprig_rod").displayName("Whirlisprig Rod");
  e.create("witherite_gear").displayName("Witherite Gear");
  e.create("witherite_plate").displayName("Witherite Plate");
  e.create("witherite_rod").displayName("Witherite Rod");
  e.create("wixie_gear").displayName("Wixie Gear");
  e.create("wixie_plate").displayName("Wixie Plate");
  e.create("wixie_rod").displayName("Wixie Rod");
  e.create("wood_rod").displayName("Wood Rod");
  e.create("zinc_plate").displayName("Zinc Plate");
  //#endregion

  //#region - Ore Processing
  /*Adamantite 1 - Raw */ e.create("raw_adamantite").displayName("Raw Adamantite");
  /*Adamantite 2 - Clump */ e.create("clump_adamantite").displayName("Adamantite Clump");
  /*Adamantite 3 - Shard */ e.create("shard_adamantite").displayName("Adamantite Shard");
  /*Adamantite 4 - Dirty Dust*/ e.create("dirty_dust_adamantite").displayName("Dirty Adamantite Dust");
  /*Adamantite 5 - Dust */ e.create("dust_adamantite").displayName("Adamantite Dust");
  /*Adamantite 6 - Crystal */ e.create("crystal_adamantite").displayName("Adamantite Crystal");
  /*Ambrosium 1 - Raw*/ e.create("raw_ambrosium").displayName("Raw Ambrosium");
  /*Ambrosium 2 - Clump*/ e.create("clump_ambrosium").displayName("Ambrosium Clump");
  /*Aquamarine 1 - Raw*/ e.create("raw_aquamarine").displayName("Raw Aquamarine");
  /*Aquamarine 2 - Clump*/ e.create("clump_aquamarine").displayName("Aquamarine Clump");
  /*Aquamarine 3 - Shard*/ e.create("shard_aquamarine").displayName("Aquamarine Shard");
  /*Aquamarine 4 - Dirty Dust*/ e.create("dirty_dust_aquamarine").displayName("Dirty Aquamarine Dust");
  /*Aquamarine 5 - Dust*/ e.create("dust_aquamarine").displayName("Aquamarine Dust");
  /*Aquamarine 6 - Crystal*/ e.create("crystal_aquamarine").displayName("Aquamarine Crystal");
  /*Bismuth 2 - Clump*/ e.create("clump_bismuth").displayName("Bismuth Clump");
  /*Bismuth 3 - Shard*/ e.create("shard_bismuth").displayName("Bismuth Shard");
  /*Bismuth 4 - Dirty Dust*/ e.create("dirty_dust_bismuth").displayName("Dirty Bismuth Dust");
  /*Bismuth 5 - Dust*/ e.create("dust_bismuth").displayName("Bismuth Dust");
  /*Bismuth 6 - Crystal*/ e.create("crystal_bismuth").displayName("Bismuth Crystal");
  /*Chorundum 1 - Raw*/ e.create("raw_chorundum").displayName("Raw Chorundum");
  /*Chorundum 2 - Clump*/ e.create("clump_chorundum").displayName("Chorundum Clump");
  /*Chorundum 3 - Shard*/ e.create("shard_chorundum").displayName("Chorundum Shard");
  /*Chorundum 4 - Dirty Dust*/ e.create("dirty_dust_chorundum").displayName("Dirty Chorundum Dust");
  /*Chorundum 5 - Dust*/ e.create("dust_chorundum").displayName("Chorundum Dust");
  /*Chorundum 6 - Crystal*/ e.create("crystal_chorundum").displayName("Chorundum Crystal");
  /*Cloggrum 2 - Clump*/ e.create("clump_cloggrum").displayName("Cloggrum Clump");
  /*Cloggrum 3 - Shard*/ e.create("shard_cloggrum").displayName("Cloggrum Shard");
  /*Cloggrum 4 - Dirty Dust*/ e.create("dirty_dust_cloggrum").displayName("Dirty Cloggrum Dust");
  /*Cloggrum 5 - Dust*/ e.create("dust_cloggrum").displayName("Cloggrum Dust");
  /*Cloggrum 6 - Crystal*/ e.create("crystal_cloggrum").displayName("Cloggrum Crystal");
  /*Coal 1 - Raw*/ e.create("raw_coal").displayName("Raw Coal");
  /*Coal 2 - Clump*/ e.create("clump_coal").displayName("Coal Clump");
  /*Coal 3 - Shard*/ e.create("shard_coal").displayName("Coal Shard");
  /*Coal 4 - Dirty Dust*/ e.create("dirty_dust_coal").displayName("Dirty Coal Dust");
  /*Coal 6 - Crystal*/ e.create("crystal_coal").displayName("Coal Crystal");
  /*Diamond 1 - Raw*/ e.create("raw_diamond").displayName("Raw Diamond");
  /*Diamond 2 - Clump*/ e.create("clump_diamond").displayName("Diamond Clump");
  /*Diamond 3 - Shard*/ e.create("shard_diamond").displayName("Diamond Shard");
  /*Diamond 4 - Dirty Dust*/ e.create("dirty_dust_diamond").displayName("Dirty Diamond Dust");
  /*Diamond 6 - Crystal*/ e.create("crystal_diamond").displayName("Diamond Crystal");
  /*Dimensional 1 - Raw*/ e.create("raw_dimensional").displayName("Raw Dimensional");
  /*Dimensional 2 - Clump*/ e.create("clump_dimensional").displayName("Dimensional Clump");
  /*Emerald 1 - Raw*/ e.create("raw_emerald").displayName("Raw Emerald");
  /*Emerald 2 - Clump*/ e.create("clump_emerald").displayName("Emerald Clump");
  /*Emerald 3 - Shard*/ e.create("shard_emerald").displayName("Emerald Shard");
  /*Emerald 4 - Dirty Dust*/ e.create("dirty_dust_emerald").displayName("Dirty Emerald Dust");
  /*Emerald 6 - Crystal*/ e.create("crystal_emerald").displayName("Emerald Crystal");
  /*Endumium 1 - Raw*/ e.create("raw_endumium").displayName("Raw Endumium");
  /*Endumium 2 - Clump*/ e.create("clump_endumium").displayName("Endumium Clump");
  /*Endumium 3 - Shard*/ e.create("shard_endumium").displayName("Endumium Shard");
  /*Endumium 4 - Dirty Dust*/ e.create("dirty_dust_endumium").displayName("Dirty Endumium Dust");
  /*Endumium 5 - Dust*/ e.create("dust_endumium").displayName("Endumium Dust");
  /*Fluorite 1 - Raw*/ e.create("raw_fluorite").displayName("Raw Fluorite");
  /*Fluorite 2 - Clump*/ e.create("clump_fluorite").displayName("Fluorite Clump");
  /*Fluorite 3 - Shard*/ e.create("shard_fluorite").displayName("Fluorite Shard");
  /*Fluorite 4 - Dirty Dust*/ e.create("dirty_dust_fluorite").displayName("Dirty Fluorite Dust");
  /*Fluorite 6 - Crystal*/ e.create("crystal_fluorite").displayName("Fluorite Crystal");
  /*Froststeel 2 - Clump*/ e.create("clump_froststeel").displayName("Froststeel Clump");
  /*Froststeel 3 - Shard*/ e.create("shard_froststeel").displayName("Froststeel Shard");
  /*Froststeel 4 - Dirty Dust*/ e.create("dirty_dust_froststeel").displayName("Dirty Froststeel Dust");
  /*Froststeel 5 - Dust*/ e.create("dust_froststeel").displayName("Froststeel Dust");
  /*Froststeel 6 - Crystal*/ e.create("crystal_froststeel").displayName("Froststeel Crystal");
  /*Gravitite 1 - Raw*/ e.create("raw_gravitite").displayName("Raw Gravitite");
  /*Gravitite 2 - Clump*/ e.create("clump_gravitite").displayName("Gravitite Clump");
  /*Gravitite 3 - Shard*/ e.create("shard_gravitite").displayName("Gravitite Shard");
  /*Gravitite 4 - Dirty Dust*/ e.create("dirty_dust_gravitite").displayName("Dirty Gravitite Dust");
  /*Gravitite 5 - Dust*/ e.create("dust_gravitite").displayName("Gravitite Dust");
  /*Gravitite 6 - Crystal*/ e.create("crystal_gravitite").displayName("Gravitite Crystal");
  /*Irradium 2 - Clump*/ e.create("clump_irradium").displayName("Irradium Clump");
  /*Irradium 3 - Shard*/ e.create("shard_irradium").displayName("Irradium Shard");
  /*Irradium 4 - Dirty Dust*/ e.create("dirty_dust_irradium").displayName("Dirty Irradium Dust");
  /*Irradium 5 - Dust*/ e.create("dust_irradium").displayName("Irradium Dust");
  /*Irradium 6 - Crystal*/ e.create("crystal_irradium").displayName("Irradium Crystal");
  /*Jade 1 - Raw*/ e.create("raw_jade").displayName("Raw Jade");
  /*Jade 2 - Clump*/ e.create("clump_jade").displayName("Jade Clump");
  /*Jade 3 - Shard*/ e.create("shard_jade").displayName("Jade Shard");
  /*Jade 4 - Dirty Dust*/ e.create("dirty_dust_jade").displayName("Dirty Jade Dust");
  /*Jade 5 - Dust*/ e.create("dust_jade").displayName("Jade Dust");
  /*Jade 6 - Crystal*/ e.create("crystal_jade").displayName("Jade Crystal");
  /*Lapis Lazuli 1 - Raw*/ e.create("raw_lapis_lazuli").displayName("Raw Lapis Lazuli");
  /*Lapis Lazuli 2 - Clump*/ e.create("clump_lapis_lazuli").displayName("Lapis Lazuli Clump");
  /*Lapis Lazuli 3 - Shard*/ e.create("shard_lapis_lazuli").displayName("Lapis Lazuli Shard");
  /*Lapis Lazuli 4 - Dirty Dust*/ e.create("dirty_dust_lapis_lazuli").displayName("Dirty Lapis Lazuli Dust");
  /*Lapis Lazuli 6 - Crystal*/ e.create("crystal_lapis_lazuli").displayName("Lapis Lazuli Crystal");
  /*Malachite 1 - Raw*/ e.create("raw_malachite").displayName("Raw Malachite");
  /*Malachite 2 - Clump*/ e.create("clump_malachite").displayName("Malachite Clump");
  /*Malachite 3 - Shard*/ e.create("shard_malachite").displayName("Malachite Shard");
  /*Malachite 4 - Dirty Dust*/ e.create("dirty_dust_malachite").displayName("Dirty Malachite Dust");
  /*Malachite 5 - Dust*/ e.create("dust_malachite").displayName("Malachite Dust");
  /*Malachite 6 - Crystal*/ e.create("crystal_malachite").displayName("Malachite Crystal");
  /*Netherite 1 - Raw*/ e.create("raw_netherite").displayName("Raw Netherite");
  /*Netherite 2 - Clump*/ e.create("clump_netherite").displayName("Netherite Clump");
  /*Netherite 3 - Shard*/ e.create("shard_netherite").displayName("Netherite Shard");
  /*Netherite 4 - Dirty Dust*/ e.create("dirty_dust_netherite").displayName("Dirty Netherite Dust");
  /*Netherite 6 - Crystal*/ e.create("crystal_netherite").displayName("Netherite Crystal");
  /*Onyx 1 - Raw*/ e.create("raw_onyx").displayName("Raw Onyx");
  /*Onyx 2 - Clump*/ e.create("clump_onyx").displayName("Onyx Clump");
  /*Onyx 3 - Shard*/ e.create("shard_onyx").displayName("Onyx Shard");
  /*Onyx 4 - Dirty Dust*/ e.create("dirty_dust_onyx").displayName("Dirty Onyx Dust");
  /*Onyx 5 - Dust*/ e.create("dust_onyx").displayName("Onyx Dust");
  /*Onyx 6 - Crystal*/ e.create("crystal_onyx").displayName("Onyx Crystal");
  /*Quartz 1 - Raw*/ e.create("raw_quartz").displayName("Raw Quartz");
  /*Quartz 2 - Clump*/ e.create("clump_quartz").displayName("Quartz Clump");
  /*Quartz 3 - Shard*/ e.create("shard_quartz").displayName("Quartz Shard");
  /*Quartz 4 - Dirty Dust*/ e.create("dirty_dust_quartz").displayName("Dirty Quartz Dust");
  /*Quartz 6 - Crystal*/ e.create("crystal_quartz").displayName("Quartz Crystal");
  /*Redstone 1 - Raw*/ e.create("raw_redstone").displayName("Raw Redstone");
  /*Redstone 2 - Clump*/ e.create("clump_redstone").displayName("Redstone Clump");
  /*Redstone 3 - Shard*/ e.create("shard_redstone").displayName("Redstone Shard");
  /*Redstone 4 - Dirty Dust*/ e.create("dirty_dust_redstone").displayName("Dirty Redstone Dust");
  /*Regalium 1 - Raw*/ e.create("raw_regalium").displayName("Raw Regalium");
  /*Regalium 2 - Clump*/ e.create("clump_regalium").displayName("Regalium Clump");
  /*Regalium 3 - Shard*/ e.create("shard_regalium").displayName("Regalium Shard");
  /*Regalium 4 - Dirty Dust*/ e.create("dirty_dust_regalium").displayName("Dirty Regalium Dust");
  /*Regalium 5 - Dust*/ e.create("dust_regalium").displayName("Regalium Dust");
  /*Ruby 1 - Raw*/ e.create("raw_ruby").displayName("Raw Ruby");
  /*Ruby 2 - Clump*/ e.create("clump_ruby").displayName("Ruby Clump");
  /*Ruby 3 - Shard*/ e.create("shard_ruby").displayName("Ruby Shard");
  /*Ruby 4 - Dirty Dust*/ e.create("dirty_dust_ruby").displayName("Dirty Ruby Dust");
  /*Ruby 5 - Dust*/ e.create("dust_ruby").displayName("Ruby Dust");
  /*Ruby 6 - Crystal*/ e.create("crystal_ruby").displayName("Ruby Crystal");
  /*Silver 2 - Clump*/ e.create("clump_silver").displayName("Silver Clump");
  /*Silver 3 - Shard*/ e.create("shard_silver").displayName("Silver Shard");
  /*Silver 4 - Dirty Dust*/ e.create("dirty_dust_silver").displayName("Dirty Silver Dust");
  /*Silver 5 - Dust*/ e.create("dust_silver").displayName("Silver Dust");
  /*Silver 6 - Crystal*/ e.create("crystal_silver").displayName("Silver Crystal");
  /*Tungsten 2 - Clump*/ e.create("clump_tungsten").displayName("Tungsten Clump");
  /*Tungsten 3 - Shard*/ e.create("shard_tungsten").displayName("Tungsten Shard");
  /*Tungsten 4 - Dirty Dust*/ e.create("dirty_dust_tungsten").displayName("Dirty Tungsten Dust");
  /*Tungsten 5 - Dust*/ e.create("dust_tungsten").displayName("Tungsten Dust");
  /*Tungsten 6 - Crystal*/ e.create("crystal_tungsten").displayName("Tungsten Crystal");
  /*Utherium 1 - Raw*/ e.create("raw_utherium").displayName("Raw Utherium");
  /*Utherium 2 - Clump*/ e.create("clump_utherium").displayName("Utherium Clump");
  /*Utherium 4 - Dirty Dust*/ e.create("dirty_dust_utherium").displayName("Dirty Utherium Dust");
  /*Utherium 5 - Dust*/ e.create("dust_utherium").displayName("Utherium Dust");
  /*Valkyrum 1 - Raw */ e.create("raw_valkyrum").displayName("Raw Valkyrum");
  /*Valkyrum 2 - Clump */ e.create("clump_valkyrum").displayName("Valkyrum Clump");
  /*Valkyrum 3 - Shard */ e.create("shard_valkyrum").displayName("Valkyrum Shard");
  /*Valkyrum 4 - Dirty Dust */ e.create("dirty_dust_valkyrum").displayName("Dirty Valkyrum Dust");
  /*Valkyrum 5 - Dust */ e.create("dust_valkyrum").displayName("Valkyrum Dust");
  /*Valkyrum 6 - Crystal */ e.create("crystal_valkyrum").displayName("Valkyrum Crystal");
  /*Zanite 1 - Raw*/ e.create("raw_zanite").displayName("Raw Zanite");
  /*Zanite 2 - Clump*/ e.create("clump_zanite").displayName("Zanite Clump");
  /*Zanite 3 - Shard*/ e.create("shard_zanite").displayName("Zanite Shard");
  /*Zanite 4 - Dirty Dust*/ e.create("dirty_dust_zanite").displayName("Dirty Zanite Dust");
  /*Zanite 5 - Dust*/ e.create("dust_zanite").displayName("Zanite Dust");
  /*Zanite 6 - Crystal*/ e.create("crystal_zanite").displayName("Zanite Crystal");
  /*Zinc 2 - Clump*/ e.create("clump_zinc").displayName("Zinc Clump");
  /*Zinc 3 - Shard*/ e.create("shard_zinc").displayName("Zinc Shard");
  /*Zinc 4 - Dirty Dust*/ e.create("dirty_dust_zinc").displayName("Dirty Zinc Dust");
  /*Zinc 5 - Dust*/ e.create("dust_zinc").displayName("Zinc Dust");
  /*Zinc 6 - Crystal*/ e.create("crystal_zinc").displayName("Zinc Crystal");
  //#endregion
});

// Custom Blocks for ModFart
StartupEvents.registry("block", e => {
  //#region - Interne à ModFart
  e.create("giant_anti_obsidian").displayName("Giant Anti-Obsidian").resistance(6000).requiresTool(true).tagBlock("minecraft:mineable/pickaxe").renderType("solid");
  e.create("giant_ultimate_obsidian").displayName("Giant Ultimate Obsidian").resistance(6000).requiresTool(true).tagBlock("minecraft:mineable/pickaxe").renderType("solid");
  e.create("block_creative").displayName("Creative Block").resistance(6000).requiresTool(true).tagBlock("minecraft:mineable/pickaxe").renderType("solid");
  //#endregion
});

// Custom Fluids for ModFart
StartupEvents.registry("fluid", e => {
  //#region - Interne à ModFart
  e.create("fluid_creative").displayName("Creative Fluid").thickTexture(0xff00ff).bucketColor(0xff00ff);
  //#endregion
});
