// Custom Items for ModFart
StartupEvents.registry('item', e => {
    // Interne à ModFart
    e.create('blank_template_trim').displayName('Blank Template Trim')
    e.create('blank_template_upgrade').displayName('Blank Template Upgrade')

    // --- Gears/Plates/Rods
    e.create('adamantite_gear').displayName('Adamantite Gear')
    e.create('adamantite_plate').displayName('Adamantite Plate')
    e.create('adamantite_rod').displayName('Adamantite Rod')
    e.create('andesite_gear').displayName('Andesite Gear')
    e.create('andesite_plate').displayName('Andesite Plate')
    e.create('andesite_rod').displayName('Andesite Rod')
    e.create('antimatter_gear').displayName('Antimatter Gear')
    e.create('antimatter_plate').displayName('Antimatter Plate')
    e.create('antimatter_rod').displayName('Antimatter Rod')
    e.create('dimensional_gear').displayName('Dimensional Gear')
    e.create('dimensional_plate').displayName('Dimensional Plate')
    e.create('dimensional_rod').displayName('Dimensional Rod')
    e.create('drygmy_gear').displayName('Drygmy Gear')
    e.create('drygmy_plate').displayName('Drygmy Plate')
    e.create('drygmy_rod').displayName('Drygmy Rod')
    e.create('echo_gear').displayName('Echo Gear')
    e.create('echo_plate').displayName('Echo Plate')
    e.create('echo_rod').displayName('Echo Rod')
    e.create('enderite_gear').displayName('Enderite Gear')
    e.create('enderite_plate').displayName('Enderite Plate')
    e.create('enderite_rod').displayName('Enderite Rod')
    e.create('endumium_gear').displayName('Endumium Gear')
    e.create('endumium_plate').displayName('Endumium Plate')
    e.create('endumium_rod').displayName('Endumium Rod')
    e.create('enhanced_redstone_gear').displayName('Enhanced Redstone Gear')
    e.create('enhanced_redstone_plate').displayName('Enhanced Redstone Plate')
    e.create('enhanced_redstone_rod').displayName('Enhanced Redstone Rod')
    e.create('experience_gear').displayName('Experience Gear').glow(true)
    e.create('experience_plate').displayName('Experience Plate').glow(true)
    e.create('experience_rod').displayName('Experience Rod').glow(true)
    e.create('fiery_rod').displayName('Fiery Rod')
    e.create('hdpe_gear').displayName('HDPE Gear')
    e.create('hdpe_plate').displayName('HDPE Plate')
    e.create('hdpe_rod').displayName('HDPE Rod')
    e.create('ironwood_rod').displayName('Ironwood Rod')
    e.create('knightmetal_rod').displayName('Knightmetal Rod')
    e.create('malachite_gear').displayName('Malachite Gear')
    e.create('malachite_plate').displayName('Malachite Plate')
    e.create('malachite_rod').displayName('Malachite Rod')
    e.create('necronium_gear').displayName('Necronium Gear')
    e.create('necronium_plate').displayName('Necronium Plate')
    e.create('necronium_rod').displayName('Necronium Rod')
    e.create('obsidian_gear').displayName('Obsidian Gear')
    e.create('obsidian_plate').displayName('Obsidian Plate')
    e.create('obsidian_rod').displayName('Obsidian Rod')
    e.create('nether_star_gear').displayName('Nether Star Gear').glow(true)
    e.create('nether_star_plate').displayName('Nether Star Plate').glow(true)
    e.create('nether_star_rod').displayName('Nether Star Rod').glow(true)
    e.create('plutonium_gear').displayName('Plutonium Gear')
    e.create('plutonium_plate').displayName('Plutonium Plate')
    e.create('plutonium_rod').displayName('Plutonium Rod')
    e.create('polonium_gear').displayName('Polonium Gear')
    e.create('polonium_plate').displayName('Polonium Plate')
    e.create('polonium_rod').displayName('Polonium Rod')
    e.create('rose_quartz_gear').displayName('Rose Quartz Gear')
    e.create('rose_quartz_plate').displayName('Rose Quartz Plate')
    e.create('rose_quartz_rod').displayName('Rose Quartz Rod')
    e.create('source_gear').displayName('Source Gear')
    e.create('source_plate').displayName('Source Plate')
    e.create('source_rod').displayName('Source Rod')
    e.create('starbuncle_gear').displayName('Starbuncle Gear')
    e.create('starbuncle_plate').displayName('Starbuncle Plate')
    e.create('starbuncle_rod').displayName('Starbuncle Rod')
    e.create('titan_gear').displayName('Titan Gear')
    e.create('titan_plate').displayName('Titan Plate')
    e.create('titan_rod').displayName('Titan Rod')
    e.create('void_steel_gear').displayName('Void Steel Gear')
    e.create('void_steel_plate').displayName('Void Steel Plate')
    e.create('void_steel_rod').displayName('Void Steel Rod')
    e.create('whirlisprig_gear').displayName('Whirlisprig Gear')
    e.create('whirlisprig_plate').displayName('Whirlisprig Plate')
    e.create('whirlisprig_rod').displayName('Whirlisprig Rod')
    e.create('wixie_gear').displayName('Wixie Gear')
    e.create('wixie_plate').displayName('Wixie Plate')
    e.create('wixie_rod').displayName('Wixie Rod')
    e.create('wood_rod').displayName('Wood Rod')

    // --- Ore Processing
    e.create('raw_ambrosium').displayName('Raw Ambrosium')
    e.create('clump_ambrosium').displayName('Ambrosium Clump')
    e.create('raw_aquamarine').displayName('Raw Aquamarine')
    e.create('clump_aquamarine').displayName('Aquamarine Clump')
    e.create('shard_aquamarine').displayName('Aquamarine Shard')
    e.create('dirty_dust_aquamarine').displayName('Dirty Aquamarine Dust')
    e.create('dust_aquamarine').displayName('Aquamarine Dust')
    e.create('crystal_aquamarine').displayName('Aquamarine Crystal')
    e.create('clump_bismuth').displayName('Bismuth Clump')
    e.create('shard_bismuth').displayName('Bismuth Shard')
    e.create('dirty_dust_bismuth').displayName('Dirty Bismuth Dust')
    e.create('dust_bismuth').displayName('Bismuth Dust')
    e.create('crystal_bismuth').displayName('Bismuth Crystal')
    e.create('raw_chorundum').displayName('Raw Chorundum')
    e.create('clump_chorundum').displayName('Chorundum Clump')
    e.create('shard_chorundum').displayName('Chorundum Shard')
    e.create('dirty_dust_chorundum').displayName('Dirty Chorundum Dust')
    e.create('dust_chorundum').displayName('Chorundum Dust')
    e.create('crystal_chorundum').displayName('Chorundum Crystal')
    e.create('clump_cloggrum').displayName('Cloggrum Clump')
    e.create('shard_cloggrum').displayName('Cloggrum Shard')
    e.create('dirty_dust_cloggrum').displayName('Dirty Cloggrum Dust')
    e.create('dust_cloggrum').displayName('Cloggrum Dust')
    e.create('crystal_cloggrum').displayName('Cloggrum Crystal')
    e.create('raw_coal').displayName('Raw Coal')
    e.create('clump_coal').displayName('Coal Clump')
    e.create('shard_coal').displayName('Coal Shard')
    e.create('dirty_dust_coal').displayName('Dirty Coal Dust')
    e.create('crystal_coal').displayName('Coal Crystal')
    e.create('raw_diamond').displayName('Raw Diamond')
    e.create('clump_diamond').displayName('Diamond Clump')
    e.create('shard_diamond').displayName('Diamond Shard')
    e.create('dirty_dust_diamond').displayName('Dirty Diamond Dust')
    e.create('crystal_diamond').displayName('Diamond Crystal')
    e.create('raw_dimensionalshard').displayName('Raw Dimensional Shard')
    e.create('clump_dimensionalshard').displayName('Dimensional Shard Clump')
    e.create('raw_emerald').displayName('Raw Emerald')
    e.create('clump_emerald').displayName('Emerald Clump')
    e.create('shard_emerald').displayName('Emerald Shard')
    e.create('dirty_dust_emerald').displayName('Dirty Emerald Dust')
    e.create('crystal_emerald').displayName('Emerald Crystal')
    e.create('raw_enderite').displayName('Raw Enderite')
    e.create('clump_enderite').displayName('Enderite Clump')
    e.create('shard_enderite').displayName('Enderite Shard')
    e.create('dirty_dust_enderite').displayName('Dirty Enderite Dust')
    e.create('dust_enderite').displayName('Enderite Dust')
    e.create('crystal_enderite').displayName('Enderite Crystal')
    e.create('raw_endumium').displayName('Raw Endumium')
    e.create('clump_endumium').displayName('Endumium Clump')
    e.create('shard_endumium').displayName('Endumium Shard')
    e.create('dirty_dust_endumium').displayName('Dirty Endumium Dust')
    e.create('dust_endumium').displayName('Endumium Dust')
    e.create('raw_fluorite').displayName('Raw Fluorite')
    e.create('clump_fluorite').displayName('Fluorite Clump')
    e.create('shard_fluorite').displayName('Fluorite Shard')
    e.create('dirty_dust_fluorite').displayName('Dirty Fluorite Dust')
    e.create('crystal_fluorite').displayName('Fluorite Crystal')
    e.create('clump_froststeel').displayName('Froststeel Clump')
    e.create('shard_froststeel').displayName('Froststeel Shard')
    e.create('dirty_dust_froststeel').displayName('Dirty Froststeel Dust')
    e.create('dust_froststeel').displayName('Froststeel Dust')
    e.create('crystal_froststeel').displayName('Froststeel Crystal')
    e.create('raw_gravitite').displayName('Raw Gravitite')
    e.create('clump_gravitite').displayName('Gravitite Clump')
    e.create('shard_gravitite').displayName('Gravitite Shard')
    e.create('dirty_dust_gravitite').displayName('Dirty Gravitite Dust')
    e.create('dust_gravitite').displayName('Gravitite Dust')
    e.create('crystal_gravitite').displayName('Gravitite Crystal')
    e.create('clump_irradium').displayName('Irradium Clump')
    e.create('shard_irradium').displayName('Irradium Shard')
    e.create('dirty_dust_irradium').displayName('Dirty Irradium Dust')
    e.create('dust_irradium').displayName('Irradium Dust')
    e.create('crystal_irradium').displayName('Irradium Crystal')
    e.create('raw_jade').displayName('Raw Jade')
    e.create('clump_jade').displayName('Jade Clump')
    e.create('shard_jade').displayName('Jade Shard')
    e.create('dirty_dust_jade').displayName('Dirty Jade Dust')
    e.create('dust_jade').displayName('Jade Dust')
    e.create('crystal_jade').displayName('Jade Crystal')
    e.create('raw_lapis_lazuli').displayName('Raw Lapis Lazuli')
    e.create('clump_lapis_lazuli').displayName('Lapis Lazuli Clump')
    e.create('shard_lapis_lazuli').displayName('Lapis Lazuli Shard')
    e.create('dirty_dust_lapis_lazuli').displayName('Dirty Lapis Lazuli Dust')
    e.create('crystal_lapis_lazuli').displayName('Lapis Lazuli Crystal')
    e.create('raw_malachite').displayName('Raw Malachite')
    e.create('clump_malachite').displayName('Malachite Clump')
    e.create('shard_malachite').displayName('Malachite Shard')
    e.create('dirty_dust_malachite').displayName('Dirty Malachite Dust')
    e.create('dust_malachite').displayName('Malachite Dust')
    e.create('crystal_malachite').displayName('Malachite Crystal')
    e.create('raw_netherite').displayName('Raw Netherite')
    e.create('clump_netherite').displayName('Netherite Clump')
    e.create('shard_netherite').displayName('Netherite Shard')
    e.create('dirty_dust_netherite').displayName('Dirty Netherite Dust')
    e.create('crystal_netherite').displayName('Netherite Crystal')
    e.create('raw_onyx').displayName('Raw Onyx')
    e.create('clump_onyx').displayName('Onyx Clump')
    e.create('shard_onyx').displayName('Onyx Shard')
    e.create('dirty_dust_onyx').displayName('Dirty Onyx Dust')
    e.create('dust_onyx').displayName('Onyx Dust')
    e.create('crystal_onyx').displayName('Onyx Crystal')
    e.create('raw_quartz').displayName('Raw Quartz')
    e.create('clump_quartz').displayName('Quartz Clump')
    e.create('shard_quartz').displayName('Quartz Shard')
    e.create('dirty_dust_quartz').displayName('Dirty Quartz Dust')
    e.create('crystal_quartz').displayName('Quartz Crystal')
    e.create('raw_redstone').displayName('Raw Redstone')
    e.create('clump_redstone').displayName('Redstone Clump')
    e.create('shard_redstone').displayName('Redstone Shard')
    e.create('dirty_dust_redstone').displayName('Dirty Redstone Dust')
    e.create('raw_regalium').displayName('Raw Regalium')
    e.create('clump_regalium').displayName('Regalium Clump')
    e.create('shard_regalium').displayName('Regalium Shard')
    e.create('dirty_dust_regalium').displayName('Dirty Regalium Dust')
    e.create('dust_regalium').displayName('Regalium Dust')
    e.create('raw_ruby').displayName('Raw Ruby')
    e.create('clump_ruby').displayName('Ruby Clump')
    e.create('shard_ruby').displayName('Ruby Shard')
    e.create('dirty_dust_ruby').displayName('Dirty Ruby Dust')
    e.create('dust_ruby').displayName('Ruby Dust')
    e.create('crystal_ruby').displayName('Ruby Crystal')
    e.create('clump_silver').displayName('Silver Clump')
    e.create('shard_silver').displayName('Silver Shard')
    e.create('dirty_dust_silver').displayName('Dirty Silver Dust')
    e.create('dust_silver').displayName('Silver Dust')
    e.create('crystal_silver').displayName('Silver Crystal')
    e.create('clump_tungsten').displayName('Tungsten Clump')
    e.create('shard_tungsten').displayName('Tungsten Shard')
    e.create('dirty_dust_tungsten').displayName('Dirty Tungsten Dust')
    e.create('dust_tungsten').displayName('Tungsten Dust')
    e.create('crystal_tungsten').displayName('Tungsten Crystal')
    e.create('raw_utherium').displayName('Raw Utherium')
    e.create('clump_utherium').displayName('Utherium Clump')
    e.create('dirty_dust_utherium').displayName('Dirty Utherium Dust')
    e.create('dust_utherium').displayName('Utherium Dust')
    e.create('raw_zanite').displayName('Raw Zanite')
    e.create('clump_zanite').displayName('Zanite Clump')
    e.create('shard_zanite').displayName('Zanite Shard')
    e.create('dirty_dust_zanite').displayName('Dirty Zanite Dust')
    e.create('dust_zanite').displayName('Zanite Dust')
    e.create('crystal_zanite').displayName('Zanite Crystal')
    e.create('clump_zinc').displayName('Zinc Clump')
    e.create('shard_zinc').displayName('Zinc Shard')
    e.create('dirty_dust_zinc').displayName('Dirty Zinc Dust')
    e.create('dust_zinc').displayName('Zinc Dust')
    e.create('crystal_zinc').displayName('Zinc Crystal')
})

// Items Modifications for ModFart
ItemEvents.modification(e => {
    e.modify('moa_decor_art:martilloycincel', i => {
        i.craftingRemainder = Item.of('moa_decor_art:martilloycincel').item
    })
    e.modify('extendedcrafting_nether_star_block', i => {
        i.craftingRemainder = Item.of('extendedcrafting_nether_star_block').item
    })
})

/* Template
    e.create('xyz_gear').displayName('xyz Gear')
    e.create('xyz_plate').displayName('xyz Plate')
    e.create('xyz_rod').displayName('xyz Rod')
    e.create('raw_xyz').displayName('Raw xyz')
    e.create('clump_xyz').displayName('xyz Clump')
    e.create('shard_xyz').displayName('xyz Shard')
    e.create('dirty_dust_xyz').displayName('Dirty xyz Dust')
    e.create('dust_xyz').displayName('xyz Dust')
    e.create('crystal_xyz').displayName('xyz Crystal')
*/