// Custom Items for ModFart
StartupEvents.registry("item", e => {
  //#region - Interne à ModFart
  e.create("blank_template_trim").displayName("Blank Template Trim")
  e.create("blank_template_upgrade").displayName("Blank Template Upgrade")
  e.create("dust_amethyst").displayName("Amethyst Dust")
  e.create("basical_apparatus").displayName("Basical Apparatus")
  e.create("magical_apparatus").displayName("Magical Apparatus")
  e.create("mechanical_apparatus").displayName("Mechanical Apparatus")
  e.create("vital_apparatus").displayName("Vital Apparatus")
  e.create("alloy_creative").displayName("Creative Alloy")
  //#endregion

  //#region - Gears/Plates/Rods
  e.create("andesite_gear").displayName("Andesite Gear")
  e.create("andesite_plate").displayName("Andesite Plate")
  e.create("andesite_rod").displayName("Andesite Rod")
  e.create("antimatter_gear").displayName("Antimatter Gear")
  e.create("antimatter_plate").displayName("Antimatter Plate")
  e.create("antimatter_rod").displayName("Antimatter Rod")
  e.create("arcane_gold_rod").displayName("Arcane Gold Rod")
  e.create("arctic_rod").displayName("Arctic Rod")
  e.create("ash_gear").displayName("Ash Gear")
  e.create("ash_rod").displayName("Ash Rod")
  e.create("cloggrum_rod").displayName("Cloggrum Rod")
  e.create("deep_gear").displayName("Deep Gear")
  e.create("deep_plate").displayName("Deep Plate")
  e.create("deep_rod").displayName("Deep Rod")
  e.create("dimensional_gear").displayName("Dimensional Gear")
  e.create("dimensional_plate").displayName("Dimensional Plate")
  e.create("dimensional_rod").displayName("Dimensional Rod")
  e.create("dragon_gear").displayName("Dragon Gear")
  e.create("dragon_plate").displayName("Dragon Plate")
  e.create("dragon_rod").displayName("Dragon Rod")
  e.create("drygmy_gear").displayName("Drygmy Gear")
  e.create("drygmy_plate").displayName("Drygmy Plate")
  e.create("drygmy_rod").displayName("Drygmy Rod")
  e.create("echo_gear").displayName("Echo Gear")
  e.create("echo_plate").displayName("Echo Plate")
  e.create("echo_rod").displayName("Echo Rod")
  e.create("enderite_gear").displayName("Enderite Gear")
  e.create("enderite_plate").displayName("Enderite Plate")
  e.create("enderite_rod").displayName("Enderite Rod")
  e.create("endumium_gear").displayName("Endumium Gear")
  e.create("endumium_plate").displayName("Endumium Plate")
  e.create("endumium_rod").displayName("Endumium Rod")
  e.create("enhanced_redstone_gear").displayName("Enhanced Redstone Gear")
  e.create("enhanced_redstone_plate").displayName("Enhanced Redstone Plate")
  e.create("enhanced_redstone_rod").displayName("Enhanced Redstone Rod")
  e.create("experience_gear").displayName("Experience Gear").glow(true)
  e.create("experience_plate").displayName("Experience Plate").glow(true)
  e.create("experience_rod").displayName("Experience Rod").glow(true)
  e.create("fiery_rod").displayName("Fiery Rod")
  e.create("forgotten_rod").displayName("Forgotten Rod")
  e.create("hdpe_gear").displayName("HDPE Gear")
  e.create("hdpe_plate").displayName("HDPE Plate")
  e.create("hdpe_rod").displayName("HDPE Rod")
  e.create("honey_gear").displayName("Honey Gear")
  e.create("honey_plate").displayName("Honey Plate")
  e.create("honey_rod").displayName("Honey Rod")
  e.create("ignitium_rod").displayName("Ignitium Rod")
  e.create("malachite_plate").displayName("Malachite Plate")
  e.create("obsidian_plate").displayName("Obsidian Plate")
  e.create("nether_star_gear").displayName("Nether Star Gear").glow(true)
  e.create("nether_star_plate").displayName("Nether Star Plate").glow(true)
  e.create("pewter_gear").displayName("Pewter Gear")
  e.create("pewter_rod").displayName("Pewter Rod")
  e.create("phantom_rod").displayName("Phantom Rod")
  e.create("plutonium_gear").displayName("Plutonium Gear")
  e.create("polonium_gear").displayName("Polonium Gear")
  e.create("rose_quartz_gear").displayName("Rose Quartz Gear")
  e.create("rose_quartz_plate").displayName("Rose Quartz Plate")
  e.create("rose_quartz_rod").displayName("Rose Quartz Rod")
  e.create("sea_gear").displayName("Sea Gear")
  e.create("sea_plate").displayName("Sea Plate")
  e.create("sea_rod").displayName("Sea Rod")
  e.create("scute_gear").displayName("Scute Gear")
  e.create("scute_plate").displayName("Scute Plate")
  e.create("scute_rod").displayName("Scute Rod")
  e.create("shadow_steel_plate").displayName("Shadow Steel Plate")
  e.create("source_gear").displayName("Source Gear")
  e.create("starbuncle_gear").displayName("Starbuncle Gear")
  e.create("starbuncle_plate").displayName("Starbuncle Plate")
  e.create("starbuncle_rod").displayName("Starbuncle Rod")
  e.create("straddlite_gear").displayName("Straddlite Gear")
  e.create("straddlite_plate").displayName("Straddlite Plate")
  e.create("straddlite_rod").displayName("Straddlite Rod")
  e.create("titan_gear").displayName("Titan Gear")
  e.create("titan_rod").displayName("Titan Rod")
  e.create("void_steel_gear").displayName("Void Steel Gear")
  e.create("void_steel_plate").displayName("Void Steel Plate")
  e.create("whirlisprig_gear").displayName("Whirlisprig Gear")
  e.create("whirlisprig_plate").displayName("Whirlisprig Plate")
  e.create("whirlisprig_rod").displayName("Whirlisprig Rod")
  e.create("witherite_gear").displayName("Witherite Gear")
  e.create("witherite_plate").displayName("Witherite Plate")
  e.create("witherite_rod").displayName("Witherite Rod")
  e.create("wixie_gear").displayName("Wixie Gear")
  e.create("wixie_plate").displayName("Wixie Plate")
  e.create("wixie_rod").displayName("Wixie Rod")
  e.create("wood_rod").displayName("Wood Rod")
  //#endregion

  //#region - Ore Processing
  e.create("raw_ambrosium").displayName("Raw Ambrosium")
  e.create("clump_ambrosium").displayName("Ambrosium Clump")
  e.create("raw_aquamarine").displayName("Raw Aquamarine")
  e.create("clump_aquamarine").displayName("Aquamarine Clump")
  e.create("shard_aquamarine").displayName("Aquamarine Shard")
  e.create("dirty_dust_aquamarine").displayName("Dirty Aquamarine Dust")
  e.create("dust_aquamarine").displayName("Aquamarine Dust")
  e.create("crystal_aquamarine").displayName("Aquamarine Crystal")
  e.create("clump_bismuth").displayName("Bismuth Clump")
  e.create("shard_bismuth").displayName("Bismuth Shard")
  e.create("dirty_dust_bismuth").displayName("Dirty Bismuth Dust")
  e.create("dust_bismuth").displayName("Bismuth Dust")
  e.create("crystal_bismuth").displayName("Bismuth Crystal")
  e.create("raw_chorundum").displayName("Raw Chorundum")
  e.create("clump_chorundum").displayName("Chorundum Clump")
  e.create("shard_chorundum").displayName("Chorundum Shard")
  e.create("dirty_dust_chorundum").displayName("Dirty Chorundum Dust")
  e.create("dust_chorundum").displayName("Chorundum Dust")
  e.create("crystal_chorundum").displayName("Chorundum Crystal")
  e.create("clump_cloggrum").displayName("Cloggrum Clump")
  e.create("shard_cloggrum").displayName("Cloggrum Shard")
  e.create("dirty_dust_cloggrum").displayName("Dirty Cloggrum Dust")
  e.create("dust_cloggrum").displayName("Cloggrum Dust")
  e.create("crystal_cloggrum").displayName("Cloggrum Crystal")
  e.create("raw_coal").displayName("Raw Coal")
  e.create("clump_coal").displayName("Coal Clump")
  e.create("shard_coal").displayName("Coal Shard")
  e.create("dirty_dust_coal").displayName("Dirty Coal Dust")
  e.create("crystal_coal").displayName("Coal Crystal")
  e.create("raw_diamond").displayName("Raw Diamond")
  e.create("clump_diamond").displayName("Diamond Clump")
  e.create("shard_diamond").displayName("Diamond Shard")
  e.create("dirty_dust_diamond").displayName("Dirty Diamond Dust")
  e.create("crystal_diamond").displayName("Diamond Crystal")
  e.create("raw_dimensional").displayName("Raw Dimensional")
  e.create("clump_dimensional").displayName("Dimensional Clump")
  e.create("raw_emerald").displayName("Raw Emerald")
  e.create("clump_emerald").displayName("Emerald Clump")
  e.create("shard_emerald").displayName("Emerald Shard")
  e.create("dirty_dust_emerald").displayName("Dirty Emerald Dust")
  e.create("crystal_emerald").displayName("Emerald Crystal")
  e.create("raw_enderite").displayName("Raw Enderite")
  e.create("clump_enderite").displayName("Enderite Clump")
  e.create("shard_enderite").displayName("Enderite Shard")
  e.create("dirty_dust_enderite").displayName("Dirty Enderite Dust")
  e.create("dust_enderite").displayName("Enderite Dust")
  e.create("crystal_enderite").displayName("Enderite Crystal")
  e.create("raw_endumium").displayName("Raw Endumium")
  e.create("clump_endumium").displayName("Endumium Clump")
  e.create("shard_endumium").displayName("Endumium Shard")
  e.create("dirty_dust_endumium").displayName("Dirty Endumium Dust")
  e.create("dust_endumium").displayName("Endumium Dust")
  e.create("raw_fluorite").displayName("Raw Fluorite")
  e.create("clump_fluorite").displayName("Fluorite Clump")
  e.create("shard_fluorite").displayName("Fluorite Shard")
  e.create("dirty_dust_fluorite").displayName("Dirty Fluorite Dust")
  e.create("crystal_fluorite").displayName("Fluorite Crystal")
  e.create("clump_froststeel").displayName("Froststeel Clump")
  e.create("shard_froststeel").displayName("Froststeel Shard")
  e.create("dirty_dust_froststeel").displayName("Dirty Froststeel Dust")
  e.create("dust_froststeel").displayName("Froststeel Dust")
  e.create("crystal_froststeel").displayName("Froststeel Crystal")
  e.create("raw_gravitite").displayName("Raw Gravitite")
  e.create("clump_gravitite").displayName("Gravitite Clump")
  e.create("shard_gravitite").displayName("Gravitite Shard")
  e.create("dirty_dust_gravitite").displayName("Dirty Gravitite Dust")
  e.create("dust_gravitite").displayName("Gravitite Dust")
  e.create("crystal_gravitite").displayName("Gravitite Crystal")
  e.create("clump_irradium").displayName("Irradium Clump")
  e.create("shard_irradium").displayName("Irradium Shard")
  e.create("dirty_dust_irradium").displayName("Dirty Irradium Dust")
  e.create("dust_irradium").displayName("Irradium Dust")
  e.create("crystal_irradium").displayName("Irradium Crystal")
  e.create("raw_jade").displayName("Raw Jade")
  e.create("clump_jade").displayName("Jade Clump")
  e.create("shard_jade").displayName("Jade Shard")
  e.create("dirty_dust_jade").displayName("Dirty Jade Dust")
  e.create("dust_jade").displayName("Jade Dust")
  e.create("crystal_jade").displayName("Jade Crystal")
  e.create("raw_lapis_lazuli").displayName("Raw Lapis Lazuli")
  e.create("clump_lapis_lazuli").displayName("Lapis Lazuli Clump")
  e.create("shard_lapis_lazuli").displayName("Lapis Lazuli Shard")
  e.create("dirty_dust_lapis_lazuli").displayName("Dirty Lapis Lazuli Dust")
  e.create("crystal_lapis_lazuli").displayName("Lapis Lazuli Crystal")
  e.create("raw_malachite").displayName("Raw Malachite")
  e.create("clump_malachite").displayName("Malachite Clump")
  e.create("shard_malachite").displayName("Malachite Shard")
  e.create("dirty_dust_malachite").displayName("Dirty Malachite Dust")
  e.create("dust_malachite").displayName("Malachite Dust")
  e.create("crystal_malachite").displayName("Malachite Crystal")
  e.create("raw_netherite").displayName("Raw Netherite")
  e.create("clump_netherite").displayName("Netherite Clump")
  e.create("shard_netherite").displayName("Netherite Shard")
  e.create("dirty_dust_netherite").displayName("Dirty Netherite Dust")
  e.create("crystal_netherite").displayName("Netherite Crystal")
  e.create("raw_onyx").displayName("Raw Onyx")
  e.create("clump_onyx").displayName("Onyx Clump")
  e.create("shard_onyx").displayName("Onyx Shard")
  e.create("dirty_dust_onyx").displayName("Dirty Onyx Dust")
  e.create("dust_onyx").displayName("Onyx Dust")
  e.create("crystal_onyx").displayName("Onyx Crystal")
  e.create("raw_quartz").displayName("Raw Quartz")
  e.create("clump_quartz").displayName("Quartz Clump")
  e.create("shard_quartz").displayName("Quartz Shard")
  e.create("dirty_dust_quartz").displayName("Dirty Quartz Dust")
  e.create("crystal_quartz").displayName("Quartz Crystal")
  e.create("raw_redstone").displayName("Raw Redstone")
  e.create("clump_redstone").displayName("Redstone Clump")
  e.create("shard_redstone").displayName("Redstone Shard")
  e.create("dirty_dust_redstone").displayName("Dirty Redstone Dust")
  e.create("raw_regalium").displayName("Raw Regalium")
  e.create("clump_regalium").displayName("Regalium Clump")
  e.create("shard_regalium").displayName("Regalium Shard")
  e.create("dirty_dust_regalium").displayName("Dirty Regalium Dust")
  e.create("dust_regalium").displayName("Regalium Dust")
  e.create("raw_ruby").displayName("Raw Ruby")
  e.create("clump_ruby").displayName("Ruby Clump")
  e.create("shard_ruby").displayName("Ruby Shard")
  e.create("dirty_dust_ruby").displayName("Dirty Ruby Dust")
  e.create("dust_ruby").displayName("Ruby Dust")
  e.create("crystal_ruby").displayName("Ruby Crystal")
  e.create("clump_silver").displayName("Silver Clump")
  e.create("shard_silver").displayName("Silver Shard")
  e.create("dirty_dust_silver").displayName("Dirty Silver Dust")
  e.create("dust_silver").displayName("Silver Dust")
  e.create("crystal_silver").displayName("Silver Crystal")
  e.create("clump_tungsten").displayName("Tungsten Clump")
  e.create("shard_tungsten").displayName("Tungsten Shard")
  e.create("dirty_dust_tungsten").displayName("Dirty Tungsten Dust")
  e.create("dust_tungsten").displayName("Tungsten Dust")
  e.create("crystal_tungsten").displayName("Tungsten Crystal")
  e.create("raw_utherium").displayName("Raw Utherium")
  e.create("clump_utherium").displayName("Utherium Clump")
  e.create("dirty_dust_utherium").displayName("Dirty Utherium Dust")
  e.create("dust_utherium").displayName("Utherium Dust")
  e.create("raw_zanite").displayName("Raw Zanite")
  e.create("clump_zanite").displayName("Zanite Clump")
  e.create("shard_zanite").displayName("Zanite Shard")
  e.create("dirty_dust_zanite").displayName("Dirty Zanite Dust")
  e.create("dust_zanite").displayName("Zanite Dust")
  e.create("crystal_zanite").displayName("Zanite Crystal")
  e.create("clump_zinc").displayName("Zinc Clump")
  e.create("shard_zinc").displayName("Zinc Shard")
  e.create("dirty_dust_zinc").displayName("Dirty Zinc Dust")
  e.create("dust_zinc").displayName("Zinc Dust")
  e.create("crystal_zinc").displayName("Zinc Crystal")
  //#endregion
})

// Custom Blocks for ModFart
StartupEvents.registry("block", e => {
  //#region - Interne à ModFart
  e.create("giant_anti_obsidian")
    .displayName("Giant Anti-Obsidian")
    .resistance(6000)
    .requiresTool(true)
    .tagBlock("minecraft:mineable/pickaxe")
    .renderType("solid")
  e.create("giant_ultimate_obsidian")
    .displayName("Giant Ultimate Obsidian")
    .resistance(6000)
    .requiresTool(true)
    .tagBlock("minecraft:mineable/pickaxe")
    .renderType("solid")
  e.create("block_creative")
    .displayName("Creative Block")
    .resistance(6000)
    .requiresTool(true)
    .tagBlock("minecraft:mineable/pickaxe")
    .renderType("solid")
  //#endregion
})

// Custom Fluids for ModFart
StartupEvents.registry("fluid", e => {
  //#region - Interne à ModFart
  e.create("fluid_creative").displayName("Creative Fluid").thickTexture(0xff00ff).bucketColor(0xff00ff)
  //#endregion
})
