//#region - Définition/Suppression/Masquage d'éléments dans JEI
function moreplates() {
  // Mise en place des Eléments à supprimer ou à cacher
  let unused = [
    /kubejs:allthemodium_/,
    /kubejs:aluminium_/,
    /kubejs:aquamarine_/,
    /kubejs:attuned_titanium_/,
    /kubejs:awakened_draconium_/,
    /kubejs:blue_alloy_/,
    /kubejs:certus_quartz_/,
    /kubejs:chromium_/,
    /kubejs:coalium_/,
    /kubejs:compressed_iron_/,
    /kubejs:conductive_iron_/,
    /kubejs:constantan_/,
    /kubejs:crude_steel_/,
    /kubejs:crystal_matrix_/,
    /kubejs:crystalline_/,
    /kubejs:dark_matter_/,
    /kubejs:dark_steel_/,
    /kubejs:diamondium_/,
    /kubejs:draconium_/,
    /kubejs:dragonsteel_/,
    /kubejs:dragonsteel_ice_/,
    /kubejs:ebony_psimetal_/,
    /kubejs:electrotine_/,
    /kubejs:elementium_/,
    /kubejs:emeraldium_/,
    /kubejs:enderium_/,
    /kubejs:energetic_alloy_/,
    /kubejs:energetic_silver_/,
    /kubejs:energized_gold_/,
    /kubejs:energized_steel_/,
    /kubejs:fluix_/,
    /kubejs:gaia_spirit_/,
    /kubejs:ghost_/,
    /kubejs:green_sapphire_/,
    /kubejs:imperium_/,
    /kubejs:inferium_/,
    /kubejs:infinity_/,
    /kubejs:infused_/,
    /kubejs:infused_diamondium_/,
    /kubejs:infused_emeraldium_/,
    /kubejs:infused_lapisium_/,
    /kubejs:infused_redstonium_/,
    /kubejs:insanium_/,
    /kubejs:invar_/,
    /kubejs:iron_alloy_/,
    /kubejs:ironium_/,
    /kubejs:ivory_psimetal_/,
    /kubejs:lapisium_/,
    /kubejs:lumium_/,
    /kubejs:manasteel_/,
    /kubejs:melodic_alloy_/,
    /kubejs:mystium_/,
    /kubejs:neutronium_/,
    /kubejs:nickel_/,
    /kubejs:platinum_/,
    /kubejs:prismarine_crystal_/,
    /kubejs:prosperity_/,
    /kubejs:prudentium_/,
    /kubejs:psimetal_/,
    /kubejs:pulsating_iron_/,
    /kubejs:pure_gold_/,
    /kubejs:pure_iron_/,
    /kubejs:pure_steel_/,
    /kubejs:pure_titanium_/,
    /kubejs:purple_alloy_/,
    /kubejs:quartz_enriched_/,
    /kubejs:red_alloy_/,
    /kubejs:red_ingot_/,
    /kubejs:red_matter_/,
    /kubejs:redstone_alloy_/,
    /kubejs:redstonium_/,
    /kubejs:sapphire_/,
    /kubejs:signalum_/,
    /kubejs:soularium_/,
    /kubejs:soulium_/,
    /kubejs:starmetal_/,
    /kubejs:stellar_alloy_/,
    /kubejs:supremium_/,
    /kubejs:terrasteel_/,
    /kubejs:tertium_/,
    /kubejs:titanium_/,
    /kubejs:tungsten_carbide_/,
    /kubejs:unobtainium_/,
    /kubejs:vibranium_/,
    /kubejs:vibranium_/,
    /kubejs:vibranium_allthemodium_alloy/,
    /kubejs:vibrant_alloy_/,
    /kubejs:vivid_alloy_/,
    /kubejs:tungesten_carbide_/,
    "kubejs:amethyst_gear",
    "kubejs:bismuth_gear",
    "kubejs:bismuth_rod",
    "kubejs:black_iron_gear",
    "kubejs:black_iron_rod",
    "kubejs:bronze_plate",
    "kubejs:charcoal_gear",
    "kubejs:charcoal_rod",
    "kubejs:electrum_gear",
    "kubejs:ender_gear",
    "kubejs:fiery_gear",
    "kubejs:fiery_plate",
    "kubejs:flint_gear",
    "kubejs:flint_plate",
    "kubejs:glowstone_gear",
    "kubejs:glowstone_plate",
    "kubejs:lead_plate",
    "kubejs:lead_rod",
    "kubejs:neptunium_gear",
    "kubejs:neptunium_plate",
    "kubejs:nether_quartz_gear",
    "kubejs:osmium_plate",
    "kubejs:osmium_rod",
    "kubejs:paper_gear",
    "kubejs:paper_rod",
    "kubejs:quartz_enriched_plate",
    "kubejs:quartz_enriched_rod",
    "kubejs:redstone_gear",
    "kubejs:redstone_ingot_gear",
    "kubejs:redstone_ingot_plate",
    "kubejs:ruby_gear",
    "kubejs:ruby_rod",
    "kubejs:silicon_gear",
    "kubejs:silicon_rod",
    "kubejs:silver_gear",
    "kubejs:silver_rod",
    "kubejs:tin_plate",
    "kubejs:tin_rod",
    "kubejs:tungsten_gear",
    "kubejs:tungsten_rod",
    "kubejs:uranium_plate",
    "kubejs:uranium_rod",
    "kubejs:wood_gear",
    "kubejs:wood_plate",
    "kubejs:zinc_gear",
    "kubejs:zinc_rod",
    /kubejs:brick_/,
    /kubejs:ironwood_/,
    /kubejs:knightmetal_/,
    /kubejs:nether_brick_/
  ]
  let hiding = []
  // Fonctions pour supprimer les tags et les crafts des éléments définis juste au dessus
  function handle_Tags(e) {
    e.removeAllTagsFrom(unused)
    e.add("forge:hiding", [unused, hiding])
  }
  function handle_Recipes(e) {
    e.remove([{ input: unused }, { output: unused }])
  }
  ServerEvents.tags(["item", "block"], handle_Tags)
  ServerEvents.recipes(handle_Recipes)
}
moreplates()
//#endregion

//#region - Crafts
ServerEvents.recipes(e => {})
//#endregion

//#region - Tags
ServerEvents.tags(["item", "block"], e => {})
//#endregion
