//#region - Définition/Suppression/Masquage d'éléments dans JEI
function moreplates() {
  // Mise en place des Eléments à supprimer ou à cacher
  let unused = [
    /moreplates:allthemodium_/,
    /moreplates:aluminium_/,
    /moreplates:aquamarine_/,
    /moreplates:attuned_titanium_/,
    /moreplates:awakened_draconium_/,
    /moreplates:blue_alloy_/,
    /moreplates:certus_quartz_/,
    /moreplates:chromium_/,
    /moreplates:coalium_/,
    /moreplates:compressed_iron_/,
    /moreplates:conductive_iron_/,
    /moreplates:constantan_/,
    /moreplates:crude_steel_/,
    /moreplates:crystal_matrix_/,
    /moreplates:crystalline_/,
    /moreplates:dark_matter_/,
    /moreplates:dark_steel_/,
    /moreplates:diamondium_/,
    /moreplates:draconium_/,
    /moreplates:dragonsteel_/,
    /moreplates:dragonsteel_ice_/,
    /moreplates:ebony_psimetal_/,
    /moreplates:electrotine_/,
    /moreplates:elementium_/,
    /moreplates:emeraldium_/,
    /moreplates:enderium_/,
    /moreplates:energetic_alloy_/,
    /moreplates:energetic_silver_/,
    /moreplates:energized_gold_/,
    /moreplates:energized_steel_/,
    /moreplates:fluix_/,
    /moreplates:gaia_spirit_/,
    /moreplates:ghost_/,
    /moreplates:green_sapphire_/,
    /moreplates:imperium_/,
    /moreplates:inferium_/,
    /moreplates:infinity_/,
    /moreplates:infused_/,
    /moreplates:infused_diamondium_/,
    /moreplates:infused_emeraldium_/,
    /moreplates:infused_lapisium_/,
    /moreplates:infused_redstonium_/,
    /moreplates:insanium_/,
    /moreplates:invar_/,
    /moreplates:iron_alloy_/,
    /moreplates:ironium_/,
    /moreplates:ivory_psimetal_/,
    /moreplates:lapisium_/,
    /moreplates:lumium_/,
    /moreplates:manasteel_/,
    /moreplates:melodic_alloy_/,
    /moreplates:mystium_/,
    /moreplates:neutronium_/,
    /moreplates:nickel_/,
    /moreplates:platinum_/,
    /moreplates:prismarine_crystal_/,
    /moreplates:prosperity_/,
    /moreplates:prudentium_/,
    /moreplates:psimetal_/,
    /moreplates:pulsating_iron_/,
    /moreplates:pure_gold_/,
    /moreplates:pure_iron_/,
    /moreplates:pure_steel_/,
    /moreplates:pure_titanium_/,
    /moreplates:purple_alloy_/,
    /moreplates:quartz_enriched_/,
    /moreplates:red_alloy_/,
    /moreplates:red_ingot_/,
    /moreplates:red_matter_/,
    /moreplates:redstone_alloy_/,
    /moreplates:redstonium_/,
    /moreplates:sapphire_/,
    /moreplates:signalum_/,
    /moreplates:soularium_/,
    /moreplates:soulium_/,
    /moreplates:starmetal_/,
    /moreplates:stellar_alloy_/,
    /moreplates:supremium_/,
    /moreplates:terrasteel_/,
    /moreplates:tertium_/,
    /moreplates:titanium_/,
    /moreplates:tungsten_carbide_/,
    /moreplates:unobtainium_/,
    /moreplates:vibranium_/,
    /moreplates:vibranium_/,
    /moreplates:vibranium_allthemodium_alloy/,
    /moreplates:vibrant_alloy_/,
    /moreplates:vivid_alloy_/,
    /moreplates:tungesten_carbide_/,
    "moreplates:amethyst_gear",
    "moreplates:bismuth_gear",
    "moreplates:bismuth_rod",
    "moreplates:black_iron_gear",
    "moreplates:black_iron_rod",
    "moreplates:bronze_plate",
    "moreplates:charcoal_gear",
    "moreplates:charcoal_rod",
    "moreplates:electrum_gear",
    "moreplates:ender_gear",
    "moreplates:fiery_gear",
    "moreplates:fiery_plate",
    "moreplates:flint_gear",
    "moreplates:flint_plate",
    "moreplates:glowstone_gear",
    "moreplates:glowstone_plate",
    "moreplates:lead_plate",
    "moreplates:lead_rod",
    "moreplates:neptunium_gear",
    "moreplates:neptunium_plate",
    "moreplates:nether_quartz_gear",
    "moreplates:osmium_plate",
    "moreplates:osmium_rod",
    "moreplates:paper_gear",
    "moreplates:paper_rod",
    "moreplates:quartz_enriched_plate",
    "moreplates:quartz_enriched_rod",
    "moreplates:redstone_gear",
    "moreplates:redstone_ingot_gear",
    "moreplates:redstone_ingot_plate",
    "moreplates:ruby_gear",
    "moreplates:ruby_rod",
    "moreplates:silicon_gear",
    "moreplates:silicon_rod",
    "moreplates:silver_gear",
    "moreplates:silver_rod",
    "moreplates:tin_plate",
    "moreplates:tin_rod",
    "moreplates:tungsten_gear",
    "moreplates:tungsten_rod",
    "moreplates:uranium_plate",
    "moreplates:uranium_rod",
    "moreplates:wood_gear",
    "moreplates:wood_plate",
    "moreplates:zinc_gear",
    "moreplates:zinc_rod",
    /moreplates:brick_/,
    /moreplates:ironwood_/,
    /moreplates:knightmetal_/,
    /moreplates:nether_brick_/
  ]
  let hiding = []
  // Fonctions pour supprimer les tags et les crafts des éléments définis juste au dessus
  function handle_Tags(e) {
    e.removeAllTagsFrom(unused)
    e.add("forge:hiding", [unused, hiding])
  }
  function handle_Recipes(e) {
    e.remove([{ input: unused }, { output: unused }])
  }
  ServerEvents.tags(["item", "block"], handle_Tags)
  ServerEvents.recipes(handle_Recipes)
}
moreplates()
//#endregion

//#region - Crafts
ServerEvents.recipes(e => {})
//#endregion

//#region - Tags
ServerEvents.tags(["item", "block"], e => {})
//#endregion
