// Ores - Blocks Tags
ServerEvents.tags('block', e => {
    e.add('forge:jamd/holystone', 'aether:holystone')
    e.add('forge:jamd/stone', 'minecraft:stone')
    e.add('forge:jamd/deepslate', 'minecraft:deepslate')
    e.add('forge:jamd/radrock', 'alexscaves:radrock')
    e.add('forge:jamd/coprolith', 'alexscaves:coprolith')
    e.add('forge:jamd/galena', 'alexscaves:galena')
    e.add('forge:jamd/guanostone', 'alexscaves:guanostone')
    e.add('forge:jamd/depthrock', 'undergarden:depthrock')
    e.add('forge:jamd/shiverstone', 'undergarden:shiverstone')
    e.add('forge:jamd/netherrack', 'minecraft:netherrack')
    e.add('forge:jamd/sculk_stone', 'deeperdarker:sculk_stone')
    e.add('forge:jamd/gloomslate', 'deeperdarker:gloomslate')
    e.add('forge:jamd/soul_bricks', 'stalwart_dungeons:soul_bricks')
    e.add('forge:jamd/end_stone', 'minecraft:end_stone')
    e.add('forge:jamd/purpur_bricks', 'stalwart_dungeons:purpur_bricks')
})