// Ores - Items Tags
ServerEvents.tags('item', e => {
    e.add('forge:ores/coal', /coal_ore/)
    e.add('forge:ores/iron', /iron_ore/)
    e.add('forge:ores/copper', /copper_ore/)
    e.add('forge:ores/gold', /gold_ore/)
    e.add('forge:ores/redstone', /redstone_ore/)
    e.add('forge:ores/emerald', /emerald_ore/)
    e.add('forge:ores/lapis', /lapis_ore/)
    e.add('forge:ores/diamond', /diamond_ore/)
    e.add('forge:ores/quartz', /quartz_ore/)
    e.add('forge:ores/zinc', /zinc_ore/)
    e.add('forge:ores/malachite', /malachite_ore/)
    e.add('forge:ores/irradium', /irradium_ore/)
    e.add('forge:ores/bismuth', /bismuth_ore/)
    e.add('forge:ores/ruby', /ruby_ore/)
    e.add('forge:ores/jade', /jade_ore/)
    e.add('forge:ores/aquamarine', /aquamarine_ore/)
    e.add('forge:ores/onyx', /onyx_ore/)
    e.add('forge:ores/silver', /silver_ore/)
    e.add('forge:ores/dimensional_shard', ['rftoolsbase:dimensionalshard_overworld', 'rftoolsbase:dimensionalshard_nether', 'rftoolsbase:dimensionalshard_end'])
    e.add('forge:ores/tungsten', /tungsten_ore/)
    e.add('forge:ores/chorundum', /chorundum_ore/)
    e.add('forge:ores/ambrosium', /ambrosium_ore/)
    e.add('forge:ores/zanite', /zanite_ore/)
    e.add('forge:ores/gravitite', /gravitite_ore/)
    e.add('forge:ores/cloggrum', /cloggrum_ore/)
    e.add('forge:ores/froststeel', /froststeel_ore/)
    e.add('forge:ores/utherium', /utherium_ore/)
    e.add('forge:ores/regalium', /regalium_ore/)
    e.add('forge:ores/endumium', /endumium_ore/)
    e.add('forge:ores/tin', /tin_ore/)
    e.add('forge:ores/osmium', /osmium_ore/)
    e.add('forge:ores/uranium', /uranium_ore/)
    e.add('forge:ores/fluorite', /fluorite_ore/)
    e.add('forge:ores/lead', /lead_ore/)
    e.add('forge:ores/netherite', 'minecraft:ancient_debris')
    e.add('forge:ores/enderite', 'lolenderite:primordial_remnants')
})


// Ores - Blocks Tags
ServerEvents.tags('block', e => {
    e.add('forge:ores/coal', /coal_ore/)
    e.add('forge:ores/iron', /iron_ore/)
    e.add('forge:ores/copper', /copper_ore/)
    e.add('forge:ores/gold', /gold_ore/)
    e.add('forge:ores/redstone', /redstone_ore/)
    e.add('forge:ores/emerald', /emerald_ore/)
    e.add('forge:ores/lapis', /lapis_ore/)
    e.add('forge:ores/diamond', /diamond_ore/)
    e.add('forge:ores/quartz', /quartz_ore/)
    e.add('forge:ores/zinc', /zinc_ore/)
    e.add('forge:ores/malachite', /malachite_ore/)
    e.add('forge:ores/irradium', /irradium_ore/)
    e.add('forge:ores/bismuth', /bismuth_ore/)
    e.add('forge:ores/ruby', /ruby_ore/)
    e.add('forge:ores/jade', /jade_ore/)
    e.add('forge:ores/aquamarine', /aquamarine_ore/)
    e.add('forge:ores/onyx', /onyx_ore/)
    e.add('forge:ores/silver', /silver_ore/)
    e.add('forge:ores/dimensional_shard', ['rftoolsbase:dimensionalshard_overworld', 'rftoolsbase:dimensionalshard_nether', 'rftoolsbase:dimensionalshard_end'])
    e.add('forge:ores/tungsten', /tungsten_ore/)
    e.add('forge:ores/chorundum', /chorundum_ore/)
    e.add('forge:ores/ambrosium', /ambrosium_ore/)
    e.add('forge:ores/zanite', /zanite_ore/)
    e.add('forge:ores/gravitite', /gravitite_ore/)
    e.add('forge:ores/cloggrum', /cloggrum_ore/)
    e.add('forge:ores/froststeel', /froststeel_ore/)
    e.add('forge:ores/utherium', /utherium_ore/)
    e.add('forge:ores/regalium', /regalium_ore/)
    e.add('forge:ores/endumium', /endumium_ore/)
    e.add('forge:ores/tin', /tin_ore/)
    e.add('forge:ores/osmium', /osmium_ore/)
    e.add('forge:ores/uranium', /uranium_ore/)
    e.add('forge:ores/fluorite', /fluorite_ore/)
    e.add('forge:ores/lead', /lead_ore/)
    e.add('forge:ores/netherite', 'minecraft:ancient_debris')
    e.add('forge:ores/enderite', 'lolenderite:primordial_remnants')
})