// Ores
ServerEvents.tags('item', e => {
    e.add('forge:modfart/ores', ['alexscaves:galena_iron_ore', 'alexscaves:radrock_uranium_ore', 'alexscaves:guanostone_redstone_ore', 'alexscaves:coprolith_coal_ore', 'ancient_aether:aether_quartz_ore', 'ancient_aether:valkyrum_ore', 'deeperdarker:sculk_stone_coal_ore', 'deeperdarker:sculk_stone_iron_ore', 'deeperdarker:sculk_stone_copper_ore', 'minecraft:coal_ore', 'minecraft:deepslate_coal_ore', 'minecraft:iron_ore', 'minecraft:deepslate_iron_ore', 'minecraft:copper_ore', 'minecraft:deepslate_copper_ore', 'minecraft:gold_ore', 'minecraft:deepslate_gold_ore', 'minecraft:redstone_ore', 'minecraft:deepslate_redstone_ore', 'minecraft:emerald_ore', 'minecraft:deepslate_emerald_ore', 'minecraft:lapis_ore', 'minecraft:deepslate_lapis_ore', 'minecraft:diamond_ore', 'minecraft:deepslate_diamond_ore', 'minecraft:nether_gold_ore', 'minecraft:nether_quartz_ore', 'minecraft:ancient_debris', 'meadow:alpine_coal_ore', 'meadow:alpine_lapis_ore', 'meadow:alpine_gold_ore', 'meadow:alpine_emerald_ore', 'meadow:alpine_iron_ore', 'meadow:alpine_copper_ore', 'meadow:alpine_diamond_ore', 'meadow:alpine_redstone_ore', 'epicsamurai:onyx_ore', 'epicsamurai:deepslate_onyx_ore', 'epicsamurai:silver_ore', 'epicsamurai:deepslate_silver_ore', 'mekanism:tin_ore', 'mekanism:deepslate_tin_ore', 'mekanism:osmium_ore', 'mekanism:deepslate_osmium_ore', 'mekanism:uranium_ore', 'deeperdarker:sculk_stone_gold_ore', 'deeperdarker:sculk_stone_redstone_ore', 'deeperdarker:sculk_stone_emerald_ore', 'deeperdarker:sculk_stone_lapis_ore', 'deeperdarker:sculk_stone_diamond_ore', 'deeperdarker:gloomslate_coal_ore', 'deeperdarker:gloomslate_iron_ore', 'deeperdarker:gloomslate_copper_ore', 'deeperdarker:gloomslate_gold_ore', 'deeperdarker:gloomslate_redstone_ore', 'deeperdarker:gloomslate_emerald_ore', 'deeperdarker:gloomslate_lapis_ore', 'deeperdarker:gloomslate_diamond_ore', 'eidolon:lead_ore', 'eidolon:deep_lead_ore', 'eidolon:silver_ore', 'eidolon:deep_silver_ore', 'lolenderite:primordial_remnants', 'enlightened_end:malachite_ore', 'enlightened_end:irradium_ore', 'enlightened_end:bismuth_ore', 'epicsamurai:ruby_ore', 'epicsamurai:deepslate_ruby_ore', 'epicsamurai:jade_ore', 'epicsamurai:deepslate_jade_ore', 'epicsamurai:aquamarine_ore', 'epicsamurai:deepslate_aquamarine_ore', 'undergarden:depthrock_regalium_ore', 'undergarden:shiverstone_regalium_ore', 'mekanism:deepslate_uranium_ore', 'mekanism:fluorite_ore', 'mekanism:deepslate_fluorite_ore', 'mekanism:lead_ore', 'mekanism:deepslate_lead_ore', 'rftoolsbase:dimensionalshard_overworld', 'rftoolsbase:dimensionalshard_nether', 'rftoolsbase:dimensionalshard_end', 'stalwart_dungeons:tungsten_ore', 'stalwart_dungeons:chorundum_ore', 'aether:ambrosium_ore', 'aether:zanite_ore', 'aether:gravitite_ore', 'farlanders:endumium_ore', 'farlanders:deepslate_endumium_ore', 'undergarden:depthrock_coal_ore', 'undergarden:shiverstone_coal_ore', 'undergarden:depthrock_iron_ore', 'undergarden:shiverstone_iron_ore', 'undergarden:depthrock_gold_ore', 'undergarden:depthrock_diamond_ore', 'undergarden:shiverstone_diamond_ore', 'undergarden:depthrock_cloggrum_ore', 'undergarden:shiverstone_cloggrum_ore', 'undergarden:shiverstone_froststeel_ore', 'undergarden:depthrock_utherium_ore', 'undergarden:shiverstone_utherium_ore'])
    e.add('', 'alexscaves:galena_iron_ore')
    e.add('', 'alexscaves:radrock_uranium_ore')
    e.add('', 'alexscaves:guanostone_redstone_ore')
    e.add('', 'alexscaves:coprolith_coal_ore')
    e.add('', 'ancient_aether:aether_quartz_ore')
    e.add('', 'ancient_aether:valkyrum_ore')
    e.add('', 'deeperdarker:sculk_stone_coal_ore')
    e.add('', 'deeperdarker:sculk_stone_iron_ore')
    e.add('', 'deeperdarker:sculk_stone_copper_ore')
    e.add('', 'minecraft:coal_ore')
    e.add('', 'minecraft:deepslate_coal_ore')
    e.add('', 'minecraft:iron_ore')
    e.add('', 'minecraft:deepslate_iron_ore')
    e.add('', 'minecraft:copper_ore')
    e.add('', 'minecraft:deepslate_copper_ore')
    e.add('', 'minecraft:gold_ore')
    e.add('', 'minecraft:deepslate_gold_ore')
    e.add('', 'minecraft:redstone_ore')
    e.add('', 'minecraft:deepslate_redstone_ore')
    e.add('', 'minecraft:emerald_ore')
    e.add('', 'minecraft:deepslate_emerald_ore')
    e.add('', 'minecraft:lapis_ore')
    e.add('', 'minecraft:deepslate_lapis_ore')
    e.add('', 'minecraft:diamond_ore')
    e.add('', 'minecraft:deepslate_diamond_ore')
    e.add('', 'minecraft:nether_gold_ore')
    e.add('', 'minecraft:nether_quartz_ore')
    e.add('', 'minecraft:ancient_debris')
    e.add('', 'meadow:alpine_coal_ore')
    e.add('', 'meadow:alpine_lapis_ore')
    e.add('', 'meadow:alpine_gold_ore')
    e.add('', 'meadow:alpine_emerald_ore')
    e.add('', 'meadow:alpine_iron_ore')
    e.add('', 'meadow:alpine_copper_ore')
    e.add('', 'meadow:alpine_diamond_ore')
    e.add('', 'meadow:alpine_redstone_ore')
    e.add('', 'epicsamurai:onyx_ore')
    e.add('', 'epicsamurai:deepslate_onyx_ore')
    e.add('', 'epicsamurai:silver_ore')
    e.add('', 'epicsamurai:deepslate_silver_ore')
    e.add('', 'mekanism:tin_ore')
    e.add('', 'mekanism:deepslate_tin_ore')
    e.add('', 'mekanism:osmium_ore')
    e.add('', 'mekanism:deepslate_osmium_ore')
    e.add('', 'mekanism:uranium_ore')
    e.add('', 'deeperdarker:sculk_stone_gold_ore')
    e.add('', 'deeperdarker:sculk_stone_redstone_ore')
    e.add('', 'deeperdarker:sculk_stone_emerald_ore')
    e.add('', 'deeperdarker:sculk_stone_lapis_ore')
    e.add('', 'deeperdarker:sculk_stone_diamond_ore')
    e.add('', 'deeperdarker:gloomslate_coal_ore')
    e.add('', 'deeperdarker:gloomslate_iron_ore')
    e.add('', 'deeperdarker:gloomslate_copper_ore')
    e.add('', 'deeperdarker:gloomslate_gold_ore')
    e.add('', 'deeperdarker:gloomslate_redstone_ore')
    e.add('', 'deeperdarker:gloomslate_emerald_ore')
    e.add('', 'deeperdarker:gloomslate_lapis_ore')
    e.add('', 'deeperdarker:gloomslate_diamond_ore')
    e.add('', 'eidolon:lead_ore')
    e.add('', 'eidolon:deep_lead_ore')
    e.add('', 'eidolon:silver_ore')
    e.add('', 'eidolon:deep_silver_ore')
    e.add('', 'lolenderite:primordial_remnants')
    e.add('', 'enlightened_end:malachite_ore')
    e.add('', 'enlightened_end:irradium_ore')
    e.add('', 'enlightened_end:bismuth_ore')
    e.add('', 'epicsamurai:ruby_ore')
    e.add('', 'epicsamurai:deepslate_ruby_ore')
    e.add('', 'epicsamurai:jade_ore')
    e.add('', 'epicsamurai:deepslate_jade_ore')
    e.add('', 'epicsamurai:aquamarine_ore')
    e.add('', 'epicsamurai:deepslate_aquamarine_ore')
    e.add('', 'undergarden:depthrock_regalium_ore')
    e.add('', 'undergarden:shiverstone_regalium_ore')
    e.add('', 'mekanism:deepslate_uranium_ore')
    e.add('', 'mekanism:fluorite_ore')
    e.add('', 'mekanism:deepslate_fluorite_ore')
    e.add('', 'mekanism:lead_ore')
    e.add('', 'mekanism:deepslate_lead_ore')
    e.add('', 'rftoolsbase:dimensionalshard_overworld')
    e.add('', 'rftoolsbase:dimensionalshard_nether')
    e.add('', 'rftoolsbase:dimensionalshard_end')
    e.add('', 'stalwart_dungeons:tungsten_ore')
    e.add('', 'stalwart_dungeons:chorundum_ore')
    e.add('', 'aether:ambrosium_ore')
    e.add('', 'aether:zanite_ore')
    e.add('', 'aether:gravitite_ore')
    e.add('', 'farlanders:endumium_ore')
    e.add('', 'farlanders:deepslate_endumium_ore')
    e.add('', 'undergarden:depthrock_coal_ore')
    e.add('', 'undergarden:shiverstone_coal_ore')
    e.add('', 'undergarden:depthrock_iron_ore')
    e.add('', 'undergarden:shiverstone_iron_ore')
    e.add('', 'undergarden:depthrock_gold_ore')
    e.add('', 'undergarden:depthrock_diamond_ore')
    e.add('', 'undergarden:shiverstone_diamond_ore')
    e.add('', 'undergarden:depthrock_cloggrum_ore')
    e.add('', 'undergarden:shiverstone_cloggrum_ore')
    e.add('', 'undergarden:shiverstone_froststeel_ore')
    e.add('', 'undergarden:depthrock_utherium_ore')
    e.add('', 'undergarden:shiverstone_utherium_ore')
})


// Raw Materials
ServerEvents.tags('item', e => {
    e.add('forge:modfart/raw_materials', ['minecraft:raw_iron', 'minecraft:raw_copper', 'minecraft:raw_gold', 'create:raw_zinc', 'enlightened_end:raw_bismuth', 'enlightened_end:raw_irradium', 'epicsamurai:raw_silver', 'mekanism:raw_osmium', 'mekanism:raw_tin', 'mekanism:raw_lead', 'mekanism:raw_uranium', 'undergarden:raw_cloggrum', 'undergarden:raw_froststeel', 'kubejs:raw_ambrosium', 'kubejs:raw_aquamarine', 'kubejs:raw_chorundum', 'kubejs:raw_coal', 'kubejs:raw_diamond', 'kubejs:raw_dimensional', 'kubejs:raw_emerald', 'kubejs:raw_enderite', 'kubejs:raw_endumium', 'kubejs:raw_fluorite', 'kubejs:raw_gravitite', 'kubejs:raw_jade', 'kubejs:raw_lapis_lazuli', 'kubejs:raw_malachite', 'kubejs:raw_netherite', 'kubejs:raw_onyx', 'kubejs:raw_quartz', 'kubejs:raw_redstone', 'kubejs:raw_regalium', 'kubejs:raw_ruby', 'kubejs:raw_utherium', 'kubejs:raw_zanite', 'stalwart_dungeons:raw_tungsten'])
    e.add('', 'minecraft:raw_iron')
    e.add('', 'minecraft:raw_copper')
    e.add('', 'minecraft:raw_gold')
    e.add('', 'create:raw_zinc')
    e.add('', 'enlightened_end:raw_bismuth')
    e.add('', 'enlightened_end:raw_irradium')
    e.add('', 'epicsamurai:raw_silver')
    e.add('', 'mekanism:raw_osmium')
    e.add('', 'mekanism:raw_tin')
    e.add('', 'mekanism:raw_lead')
    e.add('', 'mekanism:raw_uranium')
    e.add('', 'undergarden:raw_cloggrum')
    e.add('', 'undergarden:raw_froststeel')
    e.add('', 'kubejs:raw_ambrosium')
    e.add('', 'kubejs:raw_aquamarine')
    e.add('', 'kubejs:raw_chorundum')
    e.add('', 'kubejs:raw_coal')
    e.add('', 'kubejs:raw_diamond')
    e.add('', 'kubejs:raw_dimensional')
    e.add('', 'kubejs:raw_emerald')
    e.add('', 'kubejs:raw_enderite')
    e.add('', 'kubejs:raw_endumium')
    e.add('', 'kubejs:raw_fluorite')
    e.add('', 'kubejs:raw_gravitite')
    e.add('', 'kubejs:raw_jade')
    e.add('', 'kubejs:raw_lapis_lazuli')
    e.add('', 'kubejs:raw_malachite')
    e.add('', 'kubejs:raw_netherite')
    e.add('', 'kubejs:raw_onyx')
    e.add('', 'kubejs:raw_quartz')
    e.add('', 'kubejs:raw_redstone')
    e.add('', 'kubejs:raw_regalium')
    e.add('', 'kubejs:raw_ruby')
    e.add('', 'kubejs:raw_utherium')
    e.add('', 'kubejs:raw_zanite')
    e.add('', 'stalwart_dungeons:raw_tungsten')
})


// Clumps
ServerEvents.tags('item', e => {
    e.add('forge:modfart/clumps', ['mekanism:clump_iron', 'mekanism:clump_gold', 'mekanism:clump_osmium', 'mekanism:clump_copper', 'mekanism:clump_tin', 'mekanism:clump_lead', 'mekanism:clump_uranium', 'kubejs:clump_ambrosium', 'kubejs:clump_aquamarine', 'kubejs:clump_bismuth', 'kubejs:clump_chorundum', 'kubejs:clump_cloggrum', 'kubejs:clump_coal', 'kubejs:clump_diamond', 'kubejs:clump_dimensional', 'kubejs:clump_emerald', 'kubejs:clump_enderite', 'kubejs:clump_endumium', 'kubejs:clump_fluorite', 'kubejs:clump_froststeel', 'kubejs:clump_gravitite', 'kubejs:clump_irradium', 'kubejs:clump_jade', 'kubejs:clump_lapis_lazuli', 'kubejs:clump_malachite', 'kubejs:clump_netherite', 'kubejs:clump_onyx', 'kubejs:clump_quartz', 'kubejs:clump_redstone', 'kubejs:clump_regalium', 'kubejs:clump_ruby', 'kubejs:clump_silver', 'kubejs:clump_tungsten', 'kubejs:clump_utherium', 'kubejs:clump_zanite', 'kubejs:clump_zinc'])
    e.add('', 'mekanism:clump_iron')
    e.add('', 'mekanism:clump_gold')
    e.add('', 'mekanism:clump_osmium')
    e.add('', 'mekanism:clump_copper')
    e.add('', 'mekanism:clump_tin')
    e.add('', 'mekanism:clump_lead')
    e.add('', 'mekanism:clump_uranium')
    e.add('', 'kubejs:clump_ambrosium')
    e.add('', 'kubejs:clump_aquamarine')
    e.add('', 'kubejs:clump_bismuth')
    e.add('', 'kubejs:clump_chorundum')
    e.add('', 'kubejs:clump_cloggrum')
    e.add('', 'kubejs:clump_coal')
    e.add('', 'kubejs:clump_diamond')
    e.add('', 'kubejs:clump_dimensional')
    e.add('', 'kubejs:clump_emerald')
    e.add('', 'kubejs:clump_enderite')
    e.add('', 'kubejs:clump_endumium')
    e.add('', 'kubejs:clump_fluorite')
    e.add('', 'kubejs:clump_froststeel')
    e.add('', 'kubejs:clump_gravitite')
    e.add('', 'kubejs:clump_irradium')
    e.add('', 'kubejs:clump_jade')
    e.add('', 'kubejs:clump_lapis_lazuli')
    e.add('', 'kubejs:clump_malachite')
    e.add('', 'kubejs:clump_netherite')
    e.add('', 'kubejs:clump_onyx')
    e.add('', 'kubejs:clump_quartz')
    e.add('', 'kubejs:clump_redstone')
    e.add('', 'kubejs:clump_regalium')
    e.add('', 'kubejs:clump_ruby')
    e.add('', 'kubejs:clump_silver')
    e.add('', 'kubejs:clump_tungsten')
    e.add('', 'kubejs:clump_utherium')
    e.add('', 'kubejs:clump_zanite')
    e.add('', 'kubejs:clump_zinc')
})


// Shards
ServerEvents.tags('item', e => {
    e.add('forge:modfart/shards', ['mekanism:shard_iron', 'mekanism:shard_gold', 'mekanism:shard_osmium', 'mekanism:shard_copper', 'mekanism:shard_tin', 'mekanism:shard_lead', 'mekanism:shard_uranium', 'undergarden:utheric_shard', 'kubejs:shard_aquamarine', 'kubejs:shard_bismuth', 'kubejs:shard_chorundum', 'kubejs:shard_cloggrum', 'kubejs:shard_coal', 'kubejs:shard_diamond', 'kubejs:shard_emerald', 'kubejs:shard_enderite', 'kubejs:shard_endumium', 'kubejs:shard_fluorite', 'kubejs:shard_froststeel', 'kubejs:shard_gravitite', 'kubejs:shard_irradium', 'kubejs:shard_jade', 'kubejs:shard_lapis_lazuli', 'kubejs:shard_malachite', 'kubejs:shard_netherite', 'kubejs:shard_onyx', 'kubejs:shard_quartz', 'kubejs:shard_redstone', 'kubejs:shard_regalium', 'kubejs:shard_ruby', 'kubejs:shard_silver', 'kubejs:shard_tungsten', 'kubejs:shard_zanite', 'kubejs:shard_zinc'])
    e.add('', 'mekanism:shard_iron')
    e.add('', 'mekanism:shard_gold')
    e.add('', 'mekanism:shard_osmium')
    e.add('', 'mekanism:shard_copper')
    e.add('', 'mekanism:shard_tin')
    e.add('', 'mekanism:shard_lead')
    e.add('', 'mekanism:shard_uranium')
    e.add('', 'undergarden:utheric_shard')
    e.add('', 'kubejs:shard_aquamarine')
    e.add('', 'kubejs:shard_bismuth')
    e.add('', 'kubejs:shard_chorundum')
    e.add('', 'kubejs:shard_cloggrum')
    e.add('', 'kubejs:shard_coal')
    e.add('', 'kubejs:shard_diamond')
    e.add('', 'kubejs:shard_emerald')
    e.add('', 'kubejs:shard_enderite')
    e.add('', 'kubejs:shard_endumium')
    e.add('', 'kubejs:shard_fluorite')
    e.add('', 'kubejs:shard_froststeel')
    e.add('', 'kubejs:shard_gravitite')
    e.add('', 'kubejs:shard_irradium')
    e.add('', 'kubejs:shard_jade')
    e.add('', 'kubejs:shard_lapis_lazuli')
    e.add('', 'kubejs:shard_malachite')
    e.add('', 'kubejs:shard_netherite')
    e.add('', 'kubejs:shard_onyx')
    e.add('', 'kubejs:shard_quartz')
    e.add('', 'kubejs:shard_redstone')
    e.add('', 'kubejs:shard_regalium')
    e.add('', 'kubejs:shard_ruby')
    e.add('', 'kubejs:shard_silver')
    e.add('', 'kubejs:shard_tungsten')
    e.add('', 'kubejs:shard_zanite')
    e.add('', 'kubejs:shard_zinc')
})


// Dirty Dusts
ServerEvents.tags('item', e => {
    e.add('forge:modfart/dirty_dusts', ['mekanism:dirty_dust_iron', 'mekanism:dirty_dust_gold', 'mekanism:dirty_dust_osmium', 'mekanism:dirty_dust_copper', 'mekanism:dirty_dust_tin', 'mekanism:dirty_dust_lead', 'mekanism:dirty_dust_uranium', 'kubejs:dirty_dust_aquamarine', 'kubejs:dirty_dust_bismuth', 'kubejs:dirty_dust_chorundum', 'kubejs:dirty_dust_cloggrum', 'kubejs:dirty_dust_coal', 'kubejs:dirty_dust_diamond', 'kubejs:dirty_dust_emerald', 'kubejs:dirty_dust_enderite', 'kubejs:dirty_dust_endumium', 'kubejs:dirty_dust_fluorite', 'kubejs:dirty_dust_froststeel', 'kubejs:dirty_dust_gravitite', 'kubejs:dirty_dust_irradium', 'kubejs:dirty_dust_jade', 'kubejs:dirty_dust_lapis_lazuli', 'kubejs:dirty_dust_malachite', 'kubejs:dirty_dust_netherite', 'kubejs:dirty_dust_onyx', 'kubejs:dirty_dust_quartz', 'kubejs:dirty_dust_redstone', 'kubejs:dirty_dust_regalium', 'kubejs:dirty_dust_ruby', 'kubejs:dirty_dust_silver', 'kubejs:dirty_dust_tungsten', 'kubejs:dirty_dust_utherium', 'kubejs:dirty_dust_zanite', 'kubejs:dirty_dust_zinc'])
    e.add('', 'mekanism:dirty_dust_iron')
    e.add('', 'mekanism:dirty_dust_gold')
    e.add('', 'mekanism:dirty_dust_osmium')
    e.add('', 'mekanism:dirty_dust_copper')
    e.add('', 'mekanism:dirty_dust_tin')
    e.add('', 'mekanism:dirty_dust_lead')
    e.add('', 'mekanism:dirty_dust_uranium')
    e.add('', 'kubejs:dirty_dust_aquamarine')
    e.add('', 'kubejs:dirty_dust_bismuth')
    e.add('', 'kubejs:dirty_dust_chorundum')
    e.add('', 'kubejs:dirty_dust_cloggrum')
    e.add('', 'kubejs:dirty_dust_coal')
    e.add('', 'kubejs:dirty_dust_diamond')
    e.add('', 'kubejs:dirty_dust_emerald')
    e.add('', 'kubejs:dirty_dust_enderite')
    e.add('', 'kubejs:dirty_dust_endumium')
    e.add('', 'kubejs:dirty_dust_fluorite')
    e.add('', 'kubejs:dirty_dust_froststeel')
    e.add('', 'kubejs:dirty_dust_gravitite')
    e.add('', 'kubejs:dirty_dust_irradium')
    e.add('', 'kubejs:dirty_dust_jade')
    e.add('', 'kubejs:dirty_dust_lapis_lazuli')
    e.add('', 'kubejs:dirty_dust_malachite')
    e.add('', 'kubejs:dirty_dust_netherite')
    e.add('', 'kubejs:dirty_dust_onyx')
    e.add('', 'kubejs:dirty_dust_quartz')
    e.add('', 'kubejs:dirty_dust_redstone')
    e.add('', 'kubejs:dirty_dust_regalium')
    e.add('', 'kubejs:dirty_dust_ruby')
    e.add('', 'kubejs:dirty_dust_silver')
    e.add('', 'kubejs:dirty_dust_tungsten')
    e.add('', 'kubejs:dirty_dust_utherium')
    e.add('', 'kubejs:dirty_dust_zanite')
    e.add('', 'kubejs:dirty_dust_zinc')
})


// Dusts
ServerEvents.tags('item', e => {
    e.add('forge:modfart/dusts', ['mekanism:dust_fluorite', 'mekanism:dust_netherite', 'mekanism:dust_coal', 'mekanism:dust_lapis_lazuli', 'mekanism:dust_quartz', 'mekanism:dust_emerald', 'mekanism:dust_diamond', 'mekanism:dust_iron', 'mekanism:dust_gold', 'mekanism:dust_osmium', 'mekanism:dust_copper', 'mekanism:dust_tin', 'mekanism:dust_lead', 'mekanism:dust_uranium', 'kubejs:dust_aquamarine', 'kubejs:dust_bismuth', 'kubejs:dust_chorundum', 'kubejs:dust_cloggrum', 'kubejs:dust_enderite', 'kubejs:dust_endumium', 'kubejs:dust_froststeel', 'kubejs:dust_gravitite', 'kubejs:dust_irradium', 'kubejs:dust_jade', 'kubejs:dust_malachite', 'kubejs:dust_onyx', 'kubejs:dust_regalium', 'kubejs:dust_ruby', 'kubejs:dust_silver', 'kubejs:dust_tungsten', 'kubejs:dust_utherium', 'kubejs:dust_zanite', 'kubejs:dust_zinc'])
    e.add('', 'mekanism:dust_fluorite')
    e.add('', 'mekanism:dust_netherite')
    e.add('', 'mekanism:dust_coal')
    e.add('', 'mekanism:dust_lapis_lazuli')
    e.add('', 'mekanism:dust_quartz')
    e.add('', 'mekanism:dust_emerald')
    e.add('', 'mekanism:dust_diamond')
    e.add('', 'mekanism:dust_iron')
    e.add('', 'mekanism:dust_gold')
    e.add('', 'mekanism:dust_osmium')
    e.add('', 'mekanism:dust_copper')
    e.add('', 'mekanism:dust_tin')
    e.add('', 'mekanism:dust_lead')
    e.add('', 'mekanism:dust_uranium')
    e.add('', 'kubejs:dust_aquamarine')
    e.add('', 'kubejs:dust_bismuth')
    e.add('', 'kubejs:dust_chorundum')
    e.add('', 'kubejs:dust_cloggrum')
    e.add('', 'kubejs:dust_enderite')
    e.add('', 'kubejs:dust_endumium')
    e.add('', 'kubejs:dust_froststeel')
    e.add('', 'kubejs:dust_gravitite')
    e.add('', 'kubejs:dust_irradium')
    e.add('', 'kubejs:dust_jade')
    e.add('', 'kubejs:dust_malachite')
    e.add('', 'kubejs:dust_onyx')
    e.add('', 'kubejs:dust_regalium')
    e.add('', 'kubejs:dust_ruby')
    e.add('', 'kubejs:dust_silver')
    e.add('', 'kubejs:dust_tungsten')
    e.add('', 'kubejs:dust_utherium')
    e.add('', 'kubejs:dust_zanite')
    e.add('', 'kubejs:dust_zinc')
})


// Crystals
ServerEvents.tags('item', e => {
    e.add('forge:modfart/crystals', ['mekanism:crystal_iron', 'mekanism:crystal_gold', 'mekanism:crystal_osmium', 'mekanism:crystal_copper', 'mekanism:crystal_tin', 'mekanism:crystal_lead', 'mekanism:crystal_uranium', 'kubejs:crystal_aquamarine', 'kubejs:crystal_bismuth', 'kubejs:crystal_chorundum', 'kubejs:crystal_cloggrum', 'kubejs:crystal_coal', 'kubejs:crystal_diamond', 'kubejs:crystal_emerald', 'kubejs:crystal_enderite', 'kubejs:crystal_fluorite', 'kubejs:crystal_froststeel', 'kubejs:crystal_gravitite', 'kubejs:crystal_irradium', 'kubejs:crystal_jade', 'kubejs:crystal_lapis_lazuli', 'kubejs:crystal_malachite', 'kubejs:crystal_netherite', 'kubejs:crystal_onyx', 'kubejs:crystal_quartz', 'kubejs:crystal_ruby', 'kubejs:crystal_silver', 'kubejs:crystal_tungsten', 'kubejs:crystal_zanite', 'kubejs:crystal_zinc'])
    e.add('', 'mekanism:crystal_iron')
    e.add('', 'mekanism:crystal_gold')
    e.add('', 'mekanism:crystal_osmium')
    e.add('', 'mekanism:crystal_copper')
    e.add('', 'mekanism:crystal_tin')
    e.add('', 'mekanism:crystal_lead')
    e.add('', 'mekanism:crystal_uranium')
    e.add('', 'kubejs:crystal_aquamarine')
    e.add('', 'kubejs:crystal_bismuth')
    e.add('', 'kubejs:crystal_chorundum')
    e.add('', 'kubejs:crystal_cloggrum')
    e.add('', 'kubejs:crystal_coal')
    e.add('', 'kubejs:crystal_diamond')
    e.add('', 'kubejs:crystal_emerald')
    e.add('', 'kubejs:crystal_enderite')
    e.add('', 'kubejs:crystal_fluorite')
    e.add('', 'kubejs:crystal_froststeel')
    e.add('', 'kubejs:crystal_gravitite')
    e.add('', 'kubejs:crystal_irradium')
    e.add('', 'kubejs:crystal_jade')
    e.add('', 'kubejs:crystal_lapis_lazuli')
    e.add('', 'kubejs:crystal_malachite')
    e.add('', 'kubejs:crystal_netherite')
    e.add('', 'kubejs:crystal_onyx')
    e.add('', 'kubejs:crystal_quartz')
    e.add('', 'kubejs:crystal_ruby')
    e.add('', 'kubejs:crystal_silver')
    e.add('', 'kubejs:crystal_tungsten')
    e.add('', 'kubejs:crystal_zanite')
    e.add('', 'kubejs:crystal_zinc')
})


// Final Resources
ServerEvents.tags('item', e => {
    e.add('forge:modfart/final_resources', ['aether:ambrosium_shard', 'aether:enchanted_gravitite', 'aether:zanite_gemstone', 'ancient_aether:valkyrum', 'create:zinc_ingot', 'enlightened_end:bismuth_ingot', 'enlightened_end:irradium_bar', 'enlightened_end:malachite', 'epicsamurai:aquamarine', 'epicsamurai:jade', 'epicsamurai:onyx', 'epicsamurai:ruby', 'epicsamurai:silver_ingot', 'farlanders:endumium_crystal', 'lolenderite:enderite_fragment', 'minecraft:coal', 'minecraft:copper_ingot', 'minecraft:diamond', 'minecraft:emerald', 'minecraft:gold_ingot', 'minecraft:iron_ingot', 'minecraft:lapis_lazuli', 'minecraft:netherite_scrap', 'minecraft:quartz', 'minecraft:redstone', 'mekanism:fluorite_gem', 'mekanism:ingot_lead', 'mekanism:ingot_osmium', 'mekanism:ingot_tin', 'mekanism:ingot_uranium', 'rftoolsbase:dimensionalshard', 'stalwart_dungeons:chorundum', 'stalwart_dungeons:tungsten_ingot', 'undergarden:cloggrum_ingot', 'undergarden:froststeel_ingot', 'undergarden:regalium_crystal', 'undergarden:utherium_crystal'])
    e.add('', 'aether:ambrosium_shard')
    e.add('', 'aether:enchanted_gravitite')
    e.add('', 'aether:zanite_gemstone')
    e.add('', 'ancient_aether:valkyrum')
    e.add('', 'create:zinc_ingot')
    e.add('', 'enlightened_end:bismuth_ingot')
    e.add('', 'enlightened_end:irradium_bar')
    e.add('', 'enlightened_end:malachite')
    e.add('', 'epicsamurai:aquamarine')
    e.add('', 'epicsamurai:jade')
    e.add('', 'epicsamurai:onyx')
    e.add('', 'epicsamurai:ruby')
    e.add('', 'epicsamurai:silver_ingot')
    e.add('', 'farlanders:endumium_crystal')
    e.add('', 'lolenderite:enderite_fragment')
    e.add('', 'minecraft:coal')
    e.add('', 'minecraft:copper_ingot')
    e.add('', 'minecraft:diamond')
    e.add('', 'minecraft:emerald')
    e.add('', 'minecraft:gold_ingot')
    e.add('', 'minecraft:iron_ingot')
    e.add('', 'minecraft:lapis_lazuli')
    e.add('', 'minecraft:netherite_scrap')
    e.add('', 'minecraft:quartz')
    e.add('', 'minecraft:redstone')
    e.add('', 'mekanism:fluorite_gem')
    e.add('', 'mekanism:ingot_lead')
    e.add('', 'mekanism:ingot_osmium')
    e.add('', 'mekanism:ingot_tin')
    e.add('', 'mekanism:ingot_uranium')
    e.add('', 'rftoolsbase:dimensionalshard')
    e.add('', 'stalwart_dungeons:chorundum')
    e.add('', 'stalwart_dungeons:tungsten_ingot')
    e.add('', 'undergarden:cloggrum_ingot')
    e.add('', 'undergarden:froststeel_ingot')
    e.add('', 'undergarden:regalium_crystal')
    e.add('', 'undergarden:utherium_crystal')
})