// Gears
ServerEvents.tags('item', e => {
    e.add('forge:gears', [
        'kubejs:adamantite_gear',
        'moreplates:amethyst_gear',
        'kubejs:andesite_gear',
        'kubejs:antimatter_gear',
        'moreplates:aquamarine_gear',
        'moreplates:bismuth_gear',
        'moreplates:black_iron_gear',
        'moreplates:brass_gear',
        'moreplates:brick_gear',
        'moreplates:bronze_gear',
        'moreplates:charcoal_gear',
        'moreplates:coal_gear',
        'moreplates:copper_gear',
        'moreplates:crystaltine_gear',
        'moreplates:diamond_gear',
        'kubejs:dimensional_gear',
        'kubejs:drygmy_gear',
        'kubejs:echo_gear',
        'moreplates:electrum_gear',
        'moreplates:emerald_gear',
        'moreplates:ender_gear',
        'kubejs:enderite_gear',
        'kubejs:endumium_gear',
        'moreplates:enhanced_ender_gear',
        'kubejs:enhanced_redstone_gear',
        'kubejs:experience_gear',
        'moreplates:fiery_gear',
        'moreplates:flint_gear',
        'moreplates:glowstone_gear',
        'moreplates:gold_gear',
        'kubejs:hdpe_gear',
        'moreplates:iron_gear',
        'moreplates:ironwood_gear',
        'moreplates:knightmetal_gear',
        'moreplates:lapis_lazuli_gear',
        'moreplates:lead_gear',
        'kubejs:malachite_gear',
        'kubejs:necronium_gear',
        'moreplates:nether_brick_gear',
        'moreplates:nether_quartz_gear',
        'kubejs:nether_star_gear',
        'moreplates:netherite_gear',
        'kubejs:obsidian_gear',
        'moreplates:osmium_gear',
        'moreplates:paper_gear',
        'kubejs:plutonium_gear',
        'kubejs:polonium_gear',
        'moreplates:prismarine_crystal_gear',
        'moreplates:quartz_enriched_gear',
        'moreplates:redstone_gear',
        'moreplates:redstone_ingot_gear',
        'moreplates:refined_glowstone_gear',
        'moreplates:refined_obsidian_gear',
        'kubejs:rose_quartz_gear',
        'moreplates:ruby_gear',
        'moreplates:silicon_gear',
        'moreplates:silver_gear',
        'kubejs:source_gear',
        'kubejs:starbuncle_gear',
        'moreplates:steel_gear',
        'moreplates:the_ultimate_gear',
        'moreplates:tin_gear',
        'kubejs:titan_gear',
        'moreplates:tungsten_gear',
        'moreplates:uranium_gear',
        'kubejs:void_steel_gear',
        'kubejs:whirlisprig_gear',
        'kubejs:wixie_gear',
        'moreplates:wood_gear',
        'moreplates:zinc_gear'
    ])
})


// Plates
ServerEvents.tags('item', e => {
    e.add('forge:plates', [
        'kubejs:adamantite_plate',
        'moreplates:amethyst_plate',
        'kubejs:andesite_plate',
        'kubejs:antimatter_plate',
        'moreplates:aquamarine_plate',
        'moreplates:bismuth_plate',
        'moreplates:black_iron_plate',
        'moreplates:brass_plate',
        'moreplates:brick_plate',
        'moreplates:bronze_plate',
        'moreplates:charcoal_plate',
        'moreplates:coal_plate',
        'moreplates:copper_plate',
        'moreplates:crystaltine_plate',
        'moreplates:diamond_plate',
        'kubejs:dimensional_plate',
        'kubejs:drygmy_plate',
        'kubejs:echo_plate',
        'moreplates:electrum_plate',
        'moreplates:emerald_plate',
        'moreplates:ender_plate',
        'kubejs:enderite_plate',
        'kubejs:endumium_plate',
        'moreplates:enhanced_ender_plate',
        'kubejs:enhanced_redstone_plate',
        'kubejs:experience_plate',
        'moreplates:fiery_plate',
        'moreplates:flint_plate',
        'moreplates:glowstone_plate',
        'moreplates:gold_plate',
        'kubejs:hdpe_plate',
        'moreplates:iron_plate',
        'moreplates:ironwood_plate',
        'moreplates:knightmetal_plate',
        'moreplates:lapis_lazuli_plate',
        'moreplates:lead_plate',
        'kubejs:malachite_plate',
        'kubejs:necronium_plate',
        'moreplates:nether_brick_plate',
        'moreplates:nether_quartz_plate',
        'kubejs:nether_star_plate',
        'moreplates:netherite_plate',
        'kubejs:obsidian_plate',
        'moreplates:osmium_plate',
        'moreplates:paper_plate',
        'kubejs:plutonium_plate',
        'kubejs:polonium_plate',
        'moreplates:prismarine_crystal_plate',
        'moreplates:quartz_enriched_plate',
        'moreplates:redstone_plate',
        'moreplates:redstone_ingot_plate',
        'moreplates:refined_glowstone_plate',
        'moreplates:refined_obsidian_plate',
        'kubejs:rose_quartz_plate',
        'moreplates:ruby_plate',
        'moreplates:silicon_plate',
        'moreplates:silver_plate',
        'kubejs:source_plate',
        'kubejs:starbuncle_plate',
        'moreplates:steel_plate',
        'moreplates:the_ultimate_plate',
        'moreplates:tin_plate',
        'kubejs:titan_plate',
        'moreplates:tungsten_plate',
        'moreplates:uranium_plate',
        'kubejs:void_steel_plate',
        'kubejs:whirlisprig_plate',
        'kubejs:wixie_plate',
        'moreplates:zinc_plate',
        'moreplates:wood_plate'
    ])
})


// Rods
ServerEvents.tags('item', e => {
    e.add('forge:rods', [
        'kubejs:adamantite_rod',
        'moreplates:amethyst_rod',
        'kubejs:andesite_rod',
        'kubejs:antimatter_rod',
        'moreplates:aquamarine_rod',
        'moreplates:bismuth_rod',
        'moreplates:black_iron_rod',
        'moreplates:brass_rod',
        'moreplates:brick_rod',
        'moreplates:bronze_rod',
        'moreplates:charcoal_rod',
        'moreplates:coal_rod',
        'moreplates:copper_rod',
        'moreplates:crystaltine_rod',
        'moreplates:diamond_rod',
        'kubejs:dimensional_rod',
        'kubejs:drygmy_rod',
        'kubejs:echo_rod',
        'moreplates:electrum_rod',
        'moreplates:emerald_rod',
        'moreplates:ender_rod',
        'kubejs:enderite_rod',
        'kubejs:endumium_rod',
        'moreplates:enhanced_ender_rod',
        'kubejs:enhanced_redstone_rod',
        'kubejs:experience_rod',
        'kubejs:fiery_rod',
        'moreplates:flint_rod',
        'moreplates:glowstone_rod',
        'moreplates:gold_rod',
        'kubejs:hdpe_rod',
        'moreplates:iron_rod',
        'kubejs:ironwood_rod',
        'kubejs:knightmetal_rod',
        'moreplates:lapis_lazuli_rod',
        'moreplates:lead_rod',
        'kubejs:malachite_rod',
        'kubejs:necronium_rod',
        'moreplates:nether_brick_rod',
        'moreplates:nether_quartz_rod',
        'kubejs:nether_star_rod',
        'moreplates:netherite_rod',
        'kubejs:obsidian_rod',
        'moreplates:osmium_rod',
        'moreplates:paper_rod',
        'kubejs:plutonium_rod',
        'kubejs:polonium_rod',
        'moreplates:prismarine_crystal_rod',
        'moreplates:quartz_enriched_rod',
        'moreplates:redstone_rod',
        'moreplates:redstone_ingot_rod',
        'moreplates:refined_glowstone_rod',
        'moreplates:refined_obsidian_rod',
        'kubejs:rose_quartz_rod',
        'moreplates:ruby_rod',
        'moreplates:silicon_rod',
        'moreplates:silver_rod',
        'kubejs:source_rod',
        'kubejs:starbuncle_rod',
        'moreplates:steel_rod',
        'moreplates:the_ultimate_rod',
        'moreplates:tin_rod',
        'kubejs:titan_rod',
        'moreplates:tungsten_rod',
        'moreplates:uranium_rod',
        'kubejs:void_steel_rod',
        'kubejs:whirlisprig_rod',
        'kubejs:wixie_rod',
        'moreplates:zinc_rod',
        'kubejs:wood_rod'
    ])
})


// Raws
ServerEvents.tags('item', e => {
    e.add('forge:raw_materials', [
        'kubejs:raw_ambrosium',
        'kubejs:raw_aquamarine',
        'kubejs:raw_chorundum',
        'kubejs:raw_coal',
        'kubejs:raw_diamond',
        'kubejs:raw_dimensionalshard',
        'kubejs:raw_emerald',
        'kubejs:raw_enderite',
        'kubejs:raw_endumium',
        'kubejs:raw_fluorite',
        'kubejs:raw_gravitite',
        'kubejs:raw_jade',
        'kubejs:raw_lapis_lazuli',
        'kubejs:raw_malachite',
        'kubejs:raw_netherite',
        'kubejs:raw_onyx',
        'kubejs:raw_quartz',
        'kubejs:raw_redstone',
        'kubejs:raw_regalium',
        'kubejs:raw_ruby',
        'kubejs:raw_utherium',
        'kubejs:raw_zanite',
        'enlightened_end:raw_irradium',
        'enlightened_end:raw_bismuth',
        'stalwart_dungeon:raw_tungsten'
    ])
})


// Clumps
ServerEvents.tags('item', e => {
    e.add('mekanism:clumps', [
        'kubejs:clump_ambrosium',
        'kubejs:clump_aquamarine',
        'kubejs:clump_bismuth',
        'kubejs:clump_chorundum',
        'kubejs:clump_cloggrum',
        'kubejs:clump_coal',
        'kubejs:clump_diamond',
        'kubejs:clump_dimensionalshard',
        'kubejs:clump_emerald',
        'kubejs:clump_enderite',
        'kubejs:clump_endumium',
        'kubejs:clump_fluorite',
        'kubejs:clump_froststeel',
        'kubejs:clump_gravitite',
        'kubejs:clump_irradium',
        'kubejs:clump_jade',
        'kubejs:clump_lapis_lazuli',
        'kubejs:clump_malachite',
        'kubejs:clump_netherite',
        'kubejs:clump_onyx',
        'kubejs:clump_quartz',
        'kubejs:clump_redstone',
        'kubejs:clump_regalium',
        'kubejs:clump_ruby',
        'kubejs:clump_silver',
        'kubejs:clump_tungsten',
        'kubejs:clump_utherium',
        'kubejs:clump_zanite',
        'kubejs:clump_zinc'
    ])
})


// Shards
ServerEvents.tags('item', e => {
    e.add('mekanism:shards', [
        'kubejs:shard_aquamarine',
        'kubejs:shard_bismuth',
        'kubejs:shard_chorundum',
        'kubejs:shard_cloggrum',
        'kubejs:shard_coal',
        'kubejs:shard_diamond',
        'kubejs:shard_emerald',
        'kubejs:shard_enderite',
        'kubejs:shard_endumium',
        'kubejs:shard_fluorite',
        'kubejs:shard_froststeel',
        'kubejs:shard_gravitite',
        'kubejs:shard_irradium',
        'kubejs:shard_jade',
        'kubejs:shard_lapis_lazuli',
        'kubejs:shard_malachite',
        'kubejs:shard_netherite',
        'kubejs:shard_onyx',
        'kubejs:shard_quartz',
        'kubejs:shard_redstone',
        'kubejs:shard_regalium',
        'kubejs:shard_ruby',
        'kubejs:shard_silver',
        'kubejs:shard_tungsten',
        'kubejs:shard_zanite',
        'kubejs:shard_zinc', 
        'rftoolsbase:dimensionalshard',
        'aether:ambrosium_shard',
        'undergarden:utheric_shard'
    ])
})


// Dirty Dusts
ServerEvents.tags('item', e => {
    e.add('mekanism:dirty_dusts', [
        'kubejs:dirty_dust_aquamarine',
        'kubejs:dirty_dust_bismuth',
        'kubejs:dirty_dust_chorundum',
        'kubejs:dirty_dust_cloggrum',
        'kubejs:dirty_dust_coal',
        'kubejs:dirty_dust_diamond',
        'kubejs:dirty_dust_emerald',
        'kubejs:dirty_dust_enderite',
        'kubejs:dirty_dust_endumium',
        'kubejs:dirty_dust_fluorite',
        'kubejs:dirty_dust_froststeel',
        'kubejs:dirty_dust_gravitite',
        'kubejs:dirty_dust_irradium',
        'kubejs:dirty_dust_jade',
        'kubejs:dirty_dust_lapis_lazuli',
        'kubejs:dirty_dust_malachite',
        'kubejs:dirty_dust_netherite',
        'kubejs:dirty_dust_onyx',
        'kubejs:dirty_dust_quartz',
        'kubejs:dirty_dust_redstone',
        'kubejs:dirty_dust_regalium',
        'kubejs:dirty_dust_ruby',
        'kubejs:dirty_dust_silver',
        'kubejs:dirty_dust_tungsten',
        'kubejs:dirty_dust_utherium',
        'kubejs:dirty_dust_zanite',
        'kubejs:dirty_dust_zinc'
    ])
})


// Dusts
ServerEvents.tags('item', e => {
    e.add('forge:dusts', [
        'kubejs:dust_aquamarine',
        'kubejs:dust_bismuth',
        'kubejs:dust_chorundum',
        'kubejs:dust_cloggrum',
        'kubejs:dust_enderite',
        'kubejs:dust_endumium',
        'kubejs:dust_froststeel',
        'kubejs:dust_gravitite',
        'kubejs:dust_irradium',
        'kubejs:dust_jade',
        'kubejs:dust_malachite',
        'kubejs:dust_onyx',
        'kubejs:dust_regalium',
        'kubejs:dust_ruby',
        'kubejs:dust_silver',
        'kubejs:dust_tungsten',
        'kubejs:dust_utherium',
        'kubejs:dust_zanite',
        'kubejs:dust_zinc'
    ])
})


// Crystals
ServerEvents.tags('item', e => {
    e.add('mekanism:crystals', [
        'kubejs:crystal_aquamarine',
        'kubejs:crystal_bismuth',
        'kubejs:crystal_chorundum',
        'kubejs:crystal_cloggrum',
        'kubejs:crystal_coal',
        'kubejs:crystal_diamond',
        'kubejs:crystal_emerald',
        'kubejs:crystal_enderite',
        'kubejs:crystal_fluorite',
        'kubejs:crystal_froststeel',
        'kubejs:crystal_gravitite',
        'kubejs:crystal_irradium',
        'kubejs:crystal_jade',
        'kubejs:crystal_lapis_lazuli',
        'kubejs:crystal_malachite',
        'kubejs:crystal_netherite',
        'kubejs:crystal_onyx',
        'kubejs:crystal_quartz',
        'kubejs:crystal_ruby',
        'kubejs:crystal_silver',
        'kubejs:crystal_tungsten',
        'kubejs:crystal_zanite',
        'kubejs:crystal_zinc', 
        'undergarden:utherium_crystal',
        'undergarden:regalium_crystal',
        'farlanders:endumium_crystal'
    ])
})